import type { SeedPlace } from "../places";

export const PLACES: SeedPlace[] = [
  {
    key: "chateau-du-moulin",
    name: "Château du Moulin",
    category: "chateaux",
    commune: "Lassay-sur-Croisne",
    lat: 47.3686387,
    lng: 1.6105524,
    driveKm: 14,
    driveMin: 21,
    website: "https://chateaudumoulin.fr/",
    summary:
      "Manoir de brique et pierre entouré de douves, bâti à la fin du XVe siècle en Sologne, ouvert à la visite.",
    summaryEn:
      "Brick and stone moated manor built in the late 15th century in the Sologne, open to visitors.",
  },
  {
    key: "selles-sur-cher",
    name: "Château de Selles-sur-Cher",
    category: "chateaux",
    commune: "Selles-sur-Cher",
    lat: 47.2741409,
    lng: 1.5495121,
    driveKm: 20,
    driveMin: 26,
    website: "https://www.chateau-selles-sur-cher.com/",
    summary:
      "Forteresse médiévale et pavillon Renaissance au bord du Cher, avec cour intérieure et cèdre classé arbre remarquable.",
    summaryEn:
      "Medieval fortress and Renaissance pavilion on the banks of the Cher, with an inner courtyard and a cedar listed as a remarkable tree.",
  },
  {
    key: "cheverny",
    name: "Château de Cheverny",
    category: "chateaux",
    commune: "Cheverny",
    lat: 47.500231,
    lng: 1.4580181,
    driveKm: 29,
    driveMin: 31,
    website: "https://www.chateau-cheverny.fr/",
    summary:
      "Château classique du XVIIe siècle toujours habité par la même famille, meublé et réputé pour son chenil de chiens de chasse.",
    summaryEn:
      "17th-century classical château still lived in by the same family, fully furnished and known for its hunting hound kennels.",
    featured: true,
  },
  {
    key: "villesavin",
    name: "Château de Villesavin",
    category: "chateaux",
    commune: "Tour-en-Sologne",
    lat: 47.546477,
    lng: 1.5141808,
    driveKm: 34,
    driveMin: 34,
    website: "https://www.chateau-de-villesavin.fr/",
    summary:
      "Château Renaissance construit pour le chantier de Chambord, avec colombier et musée de voitures à cheval.",
    summaryEn:
      "Renaissance château built for the Chambord building site, with a dovecote and a museum of horse-drawn carriages.",
  },
  {
    key: "valencay",
    name: "Château de Valençay",
    category: "chateaux",
    commune: "Valençay",
    lat: 47.15755,
    lng: 1.5629814,
    driveKm: 29,
    driveMin: 36,
    website: "https://www.chateau-valencay.fr/",
    summary:
      "Grand château Renaissance dans l'Indre, ancienne demeure de Talleyrand, entouré de jardins et d'un parc animalier.",
    summaryEn:
      "Large Renaissance château in the Indre, once home to Talleyrand, surrounded by gardens and an animal park.",
  },
  {
    key: "fougeres-sur-bievre",
    name: "Château de Fougères-sur-Bièvre",
    category: "chateaux",
    commune: "Fougères-sur-Bièvre",
    lat: 47.4476634,
    lng: 1.3439684,
    driveKm: 40,
    driveMin: 41,
    website: "https://chateau-fougeres.com/",
    summary:
      "Forteresse médiévale de la fin du XVe siècle, entre château fort et demeure Renaissance, en Loir-et-Cher.",
    summaryEn:
      "Late 15th-century medieval fortress, halfway between a fortified castle and a Renaissance residence, in Loir-et-Cher.",
  },
  {
    key: "chambord",
    name: "Château de Chambord",
    category: "chateaux",
    commune: "Chambord",
    lat: 47.6160697,
    lng: 1.5170502,
    driveKm: 40,
    driveMin: 43,
    website: "https://www.chambord.org/fr/",
    summary:
      "Plus vaste château de la Loire, chef-d'œuvre de la Renaissance au cœur d'un domaine forestier clos, avec son célèbre escalier à double révolution.",
    summaryEn:
      "The largest château of the Loire, a Renaissance masterpiece in the heart of an enclosed forest estate, with its famous double-helix staircase.",
    featured: true,
  },
  {
    key: "blois",
    name: "Château royal de Blois",
    nameEn: "Royal Château of Blois",
    category: "chateaux",
    commune: "Blois",
    lat: 47.5855886,
    lng: 1.330242,
    driveKm: 45,
    driveMin: 45,
    website: "https://www.chateaudeblois.fr/",
    summary:
      "Château royal réunissant quatre ailes d'époques différentes, du gothique au classique, au centre de la ville de Blois.",
    summaryEn:
      "Royal château combining four wings from different periods, from Gothic to classical, in the centre of Blois.",
    events: [
      {
        name: "Son et lumière",
        period: "d'avril à septembre",
        periodEn: "from April to September",
      },
    ],
  },
  {
    key: "chenonceau",
    name: "Château de Chenonceau",
    category: "chateaux",
    commune: "Chenonceaux",
    lat: 47.3246221,
    lng: 1.0704175,
    driveKm: 62,
    driveMin: 52,
    website: "https://www.chenonceau.com/",
    summary:
      "Château bâti en partie sur le Cher, surnommé le château des Dames, avec galerie sur la rivière et jardins.",
    summaryEn:
      "Château built partly over the Cher, nicknamed the Ladies' Château, with a gallery above the river and gardens.",
    featured: true,
  },
  {
    key: "ferte-saint-aubin",
    name: "Château de la Ferté-Saint-Aubin",
    category: "chateaux",
    commune: "La Ferté-Saint-Aubin",
    lat: 47.7264315,
    lng: 1.9436057,
    driveKm: 47,
    driveMin: 54,
    website: "https://www.chateau-ferte.com/fr",
    summary:
      "Château du XVIIe siècle dans le Loiret, accessible à la visite et proposant aussi un escape game dans ses salles.",
    summaryEn:
      "17th-century château in the Loiret, open to visitors and also offering an escape game in its rooms.",
  },
  {
    key: "chaumont-sur-loire",
    name: "Domaine de Chaumont-sur-Loire",
    category: "chateaux",
    commune: "Chaumont-sur-Loire",
    lat: 47.479146,
    lng: 1.1815237,
    driveKm: 55,
    driveMin: 58,
    website: "https://www.domaine-chaumont.fr/",
    summary:
      "Château dominant la Loire, accompagné d'un parc, de grandes écuries et d'un Festival international des jardins.",
    summaryEn:
      "Château overlooking the Loire, with a park, large stables and an International Garden Festival.",
  },
  {
    key: "piscine-romorantin",
    name: "Complexe aquatique Alain Calmat",
    category: "famille",
    commune: "Romorantin-Lanthenay",
    lat: 47.368409,
    lng: 1.7377343,
    driveKm: 2,
    driveMin: 3,
    website:
      "https://ccrm41.fr/vivre-et-habiter/equipement-sportifs-et-culturels/",
    summary:
      "Piscine couverte de la ville (bassins de 25 x 12,5 m et 12,5 x 12,5 m) associée à une patinoire, avenue de Paris.",
    summaryEn:
      "The town's indoor swimming pool (25 x 12.5 m and 12.5 x 12.5 m pools) with an ice rink, on avenue de Paris.",
  },
  {
    key: "beauval",
    name: "ZooParc de Beauval",
    nameEn: "Beauval Zoo",
    category: "famille",
    commune: "Saint-Aignan",
    lat: 47.2464882,
    lng: 1.34809,
    driveKm: 48,
    driveMin: 38,
    website: "https://www.zoobeauval.com/",
    summary:
      "Parc zoologique de Saint-Aignan, l'un des plus grands de France, réputé pour ses pandas géants et ses lamantins.",
    summaryEn:
      "Zoo in Saint-Aignan, one of the largest in France, known for its giant pandas and manatees.",
    featured: true,
  },
  {
    key: "center-parcs",
    name: "Center Parcs Les Hauts de Bruyères",
    category: "famille",
    commune: "Chaumont-sur-Tharonne",
    lat: 47.6210542,
    lng: 1.9326497,
    driveKm: 37,
    driveMin: 42,
    website: "https://www.centerparcs.fr/",
    summary:
      "Domaine de vacances ouvert en 1993 en forêt solognote, avec Aqua Mundo et activités familiales.",
    summaryEn:
      "Holiday village opened in 1993 in the Sologne forest, with Aqua Mundo and family activities.",
  },
  {
    key: "pole-des-etoiles",
    name: "Pôle des Étoiles",
    nameEn: "Pôle des Étoiles astronomy centre",
    category: "famille",
    commune: "Nançay",
    lat: 47.3677276,
    lng: 2.1953488,
    driveKm: 41,
    driveMin: 42,
    website: "https://www.poledesetoiles.fr/",
    summary:
      "Site d'astronomie de Nançay (Cher) proposant des soirées d'observation du ciel et une exposition de rétrogaming.",
    summaryEn:
      "Astronomy site in Nançay (Cher) offering stargazing evenings and a retro gaming exhibition.",
  },
  {
    key: "parc-equestre-federal",
    name: "Parc équestre fédéral",
    nameEn: "Federal Equestrian Park",
    category: "equestre",
    commune: "Lamotte-Beuvron",
    lat: 47.6020829,
    lng: 2.0072329,
    driveKm: 41,
    driveMin: 43,
    website: "https://www.ffe.com/parc-equestre",
    summary:
      "Site de la Fédération française d'équitation à Lamotte-Beuvron, plus grand parc équestre d'Europe, hôte des grands rendez-vous annuels.",
    summaryEn:
      "Site of the French Equestrian Federation in Lamotte-Beuvron, the largest equestrian park in Europe, host of major annual events.",
    featured: true,
    events: [
      { name: "Grand Tournoi", period: "mi-mai", periodEn: "mid-May" },
      { name: "Game Fair", period: "mi-juin", periodEn: "mid-June" },
      {
        name: "Generali Open de France, poneys",
        period: "début juillet",
        periodEn: "early July",
      },
      {
        name: "Generali Open de France, clubs",
        period: "mi-juillet",
        periodEn: "mid-July",
      },
    ],
  },
  {
    key: "chambord-spectacle-equestre",
    name: "Chambord, l'histoire à cheval",
    nameEn: "Chambord, history on horseback",
    category: "equestre",
    commune: "Chambord",
    lat: 47.6160697,
    lng: 1.5170502,
    driveKm: 40,
    driveMin: 43,
    website: "https://www.chambord.org/fr/",
    summary:
      "Spectacle équestre de Mario Luraschi dans les écuries du maréchal de Saxe.",
    summaryEn:
      "Equestrian show by Mario Luraschi in the stables of Marshal de Saxe.",
    events: [
      {
        name: "Spectacle équestre",
        period: "d'avril à début novembre",
        periodEn: "from April to early November",
      },
    ],
  },
  {
    key: "marche",
    name: "Marché de la Halle",
    nameEn: "Halle market",
    category: "romorantin",
    commune: "Romorantin-Lanthenay",
    lat: 47.361013,
    lng: 1.74224,
    driveKm: 1,
    driveMin: 1,
    website: "https://www.romorantin.com/",
    summary: "Marché sous la Halle du centre-ville de Romorantin-Lanthenay.",
    summaryEn:
      "Market under the Halle in the town centre of Romorantin-Lanthenay.",
  },
  {
    key: "musee-de-sologne",
    name: "Musée de Sologne",
    nameEn: "Sologne Museum",
    category: "romorantin",
    commune: "Romorantin-Lanthenay",
    lat: 47.3571095,
    lng: 1.7432124,
    driveKm: 1,
    driveMin: 2,
    website: "https://museedesologne.romorantin.com/",
    summary:
      "Musée municipal installé au Moulin du Chapitre sur la Sauldre, consacré à l'histoire, aux traditions et à la nature de la Sologne.",
    summaryEn:
      "Municipal museum in the Moulin du Chapitre on the Sauldre, devoted to the history, traditions and nature of the Sologne.",
    featured: true,
  },
  {
    key: "musee-matra",
    name: "Espace Automobiles Matra",
    nameEn: "Matra Automobile Museum",
    category: "romorantin",
    commune: "Romorantin-Lanthenay",
    lat: 47.3579412,
    lng: 1.7404594,
    driveKm: 1,
    driveMin: 2,
    website: "https://www.museematra.com/",
    summary:
      "Musée consacré aux voitures Matra, dont la Murena et l'Espace, rue des Capucins, ouvert 7 jours sur 7 en juillet et août.",
    summaryEn:
      "Museum devoted to Matra cars, including the Murena and the Espace, on rue des Capucins, open 7 days a week in July and August.",
  },
  {
    key: "office-de-tourisme",
    name: "Office de tourisme de Romorantin-Lanthenay",
    nameEn: "Romorantin-Lanthenay tourist office",
    category: "romorantin",
    commune: "Romorantin-Lanthenay",
    lat: 47.3593893,
    lng: 1.7421961,
    driveKm: 1,
    driveMin: 2,
    website: "https://www.sologne-tourisme.fr/",
    summary:
      "Office de tourisme au 32 place de la Paix, au centre-ville, pour cartes, balades au bord de la Sauldre et idées de sorties.",
    summaryEn:
      "Tourist office at 32 place de la Paix in the town centre, for maps, walks along the Sauldre and ideas for outings.",
  },
  {
    key: "veloroute-v46",
    name: "Véloroute Cœur de France à vélo (V46)",
    nameEn: "Cœur de France cycle route (V46)",
    category: "nature",
    commune: "Mennetou-sur-Cher",
    lat: 47.2691517,
    lng: 1.8669838,
    driveKm: 16,
    driveMin: 18,
    website: "https://www.canaldeberryavelo.fr/",
    summary:
      "Véloroute V46 le long du canal de Berry puis du Cher, passant par Mennetou-sur-Cher, Selles-sur-Cher et près de Beauval.",
    summaryEn:
      "V46 cycle route along the Berry canal and then the Cher, passing through Mennetou-sur-Cher, Selles-sur-Cher and close to Beauval.",
  },
  {
    key: "maison-des-etangs",
    name: "Maison des Étangs",
    nameEn: "Maison des Étangs ponds centre",
    category: "nature",
    commune: "Saint-Viâtre",
    lat: 47.5216695,
    lng: 1.9328906,
    driveKm: 24,
    driveMin: 29,
    website: "https://www.maison-des-etangs.fr/",
    summary:
      "Maison thématique sur l'histoire, l'écologie et la gestion des étangs de Sologne, avec visites guidées.",
    summaryEn:
      "Themed centre on the history, ecology and management of the Sologne ponds, with guided tours.",
    featured: true,
  },
  {
    key: "boucle-velo-cerf",
    name: "Boucle vélo Sur la piste du cerf",
    nameEn: "On the stag's trail cycle loop",
    category: "nature",
    commune: "La Marolle-en-Sologne",
    lat: 47.5825959,
    lng: 1.7753107,
    driveKm: 28,
    driveMin: 31,
    website:
      "https://www.francevelotourisme.com/itineraire/boucle-14-en-foret-sur-la-piste-du-cerf",
    summary:
      "Boucle facile de 15 km de Sologne à vélo au départ de La Marolle-en-Sologne, passant par la Maison du Cerf de Villeny.",
    summaryEn:
      "Easy 15 km cycle loop through the Sologne from La Marolle-en-Sologne, passing the Maison du Cerf in Villeny.",
  },
  {
    key: "golf-cheverny",
    name: "Golf du Château de Cheverny",
    nameEn: "Cheverny Château golf course",
    category: "nature",
    commune: "Cheverny",
    lat: 47.485323,
    lng: 1.4605111,
    driveKm: 30,
    driveMin: 33,
    website: "https://www.golf-cheverny.com/",
    summary: "Golf en Sologne dans le cadre du château de Cheverny.",
    summaryEn:
      "Golf course in the Sologne, set in the grounds of the Château de Cheverny.",
  },
  {
    key: "maison-du-cerf",
    name: "Maison du Cerf",
    nameEn: "Maison du Cerf stag museum",
    category: "nature",
    commune: "Villeny",
    lat: 47.6232002,
    lng: 1.7550053,
    driveKm: 33,
    driveMin: 36,
    website: "https://www.maisonducerf.fr/",
    summary:
      "Espace muséographique sur le cerf (vie, bois, brame), place de l'Église, pour s'initier avant d'aller écouter le brame.",
    summaryEn:
      "Museum space on the stag (life, antlers, rut), on place de l'Église, a good introduction before going to hear the rut.",
  },
  {
    key: "brame-chambord",
    name: "Brame du cerf à Chambord",
    nameEn: "Deer rut at Chambord",
    category: "nature",
    commune: "Chambord",
    lat: 47.6160697,
    lng: 1.5170502,
    driveKm: 40,
    driveMin: 43,
    website: "https://www.chambord.org/fr/",
    summary:
      "Forêt de Chambord, 700 à 900 cerfs : observatoires libres et sorties guidées pour écouter le brame de mi-septembre à mi-octobre.",
    summaryEn:
      "Chambord forest, home to 700 to 900 deer: open observatories and guided outings to hear the rut from mid-September to mid-October.",
    events: [
      {
        name: "Brame du cerf",
        period: "de mi-septembre à mi-octobre",
        periodEn: "from mid-September to mid-October",
      },
    ],
  },
  {
    key: "golf-des-etoiles",
    name: "Golf des Étoiles",
    nameEn: "Golf des Étoiles golf course",
    category: "nature",
    commune: "Nançay",
    lat: 47.3324754,
    lng: 2.2031156,
    driveKm: 43,
    driveMin: 47,
    website: "https://www.le-golf-des-etoiles.fr/",
    summary: "Golf de Nançay, en Sologne.",
    summaryEn: "Golf course in Nançay, in the Sologne.",
  },
  {
    key: "mennetou-sur-cher",
    name: "Mennetou-sur-Cher",
    category: "villages",
    commune: "Mennetou-sur-Cher",
    lat: 47.2691517,
    lng: 1.8669838,
    driveKm: 16,
    driveMin: 18,
    website: "https://www.mennetou.fr/",
    summary:
      "Cité médiévale fortifiée sur le Cher et étape de la véloroute V46.",
    summaryEn:
      "Fortified medieval town on the Cher and a stop on the V46 cycle route.",
    featured: true,
  },
  {
    key: "pierrefitte-sur-sauldre",
    name: "Pierrefitte-sur-Sauldre",
    category: "villages",
    commune: "Pierrefitte-sur-Sauldre",
    lat: 47.5133969,
    lng: 2.1513692,
    driveKm: 38,
    driveMin: 42,
    website: "https://www.pierrefitte-sur-sauldre.fr/",
    summary:
      "Village calme de Sologne avec son église Saint-Martin du XIIe siècle.",
    summaryEn:
      "Quiet Sologne village with its 12th-century Saint-Martin church.",
  },
  {
    key: "souvigny-en-sologne",
    name: "Souvigny-en-Sologne",
    category: "villages",
    commune: "Souvigny-en-Sologne",
    lat: 47.6441208,
    lng: 2.1635734,
    driveKm: 51,
    driveMin: 53,
    website: "https://www.souvigny-en-sologne.fr/",
    summary:
      "Village solognot typique, avec église et maisons autour de la place.",
    summaryEn:
      "Typical Sologne village, with a church and houses around the square.",
  },
  {
    key: "leclerc",
    name: "E.Leclerc Romorantin",
    nameEn: "E.Leclerc supermarket, Romorantin",
    category: "pratique",
    commune: "Romorantin-Lanthenay",
    lat: 47.3734419,
    lng: 1.715951,
    driveKm: 4,
    driveMin: 7,
    website: "https://www.e.leclerc/mag/e-leclerc-romorantin",
    summary:
      "Grande surface de la rue des Chardonnes pour les courses du séjour, avec drive et station-service.",
    summaryEn:
      "Large supermarket on rue des Chardonnes for the holiday shop, with click and collect and a petrol station.",
  },
  {
    key: "gare",
    name: "Gare de Romorantin",
    nameEn: "Romorantin railway station",
    category: "pratique",
    commune: "Romorantin-Lanthenay",
    lat: 47.3554036,
    lng: 1.7388706,
    driveKm: 2,
    driveMin: 3,
    website:
      "https://www.ter.sncf.com/centre-val-de-loire/se-deplacer/gares/romorantin-blanc-argent-87576025",
    summary:
      "Gare TER du boulevard Jean Jaurès, trains vers Vierzon et cars de substitution vers Salbris, Valençay et Saint-Aignan.",
    summaryEn:
      "TER station on boulevard Jean Jaurès, with trains to Vierzon and replacement coaches to Salbris, Valençay and Saint-Aignan.",
  },
  {
    key: "a85-sortie-14",
    name: "Sortie 14 de l'A85",
    nameEn: "A85 motorway, exit 14",
    category: "pratique",
    commune: "Villefranche-sur-Cher",
    lat: 47.3206171,
    lng: 1.7721917,
    driveKm: 6,
    driveMin: 8,
    website: "https://www.vinci-autoroutes.com/fr/",
    summary:
      "Échangeur Villefranche-sur-Cher / Romorantin-Lanthenay de l'A85, le plus proche du gîte, qui relie aussi l'A71 vers Orléans et Vierzon.",
    summaryEn:
      "Villefranche-sur-Cher / Romorantin-Lanthenay interchange on the A85, the closest to the cottage, which also connects to the A71 towards Orléans and Vierzon.",
  },
  {
    key: "clos-luce",
    name: "Château du Clos Lucé",
    category: "chateaux",
    commune: "Amboise",
    lat: 47.4103237,
    lng: 0.992109,
    driveKm: 71,
    driveMin: 59,
    website: "https://www.vinci-closluce.com/",
    summary:
      "Dernière demeure de Léonard de Vinci, qui y vécut de 1516 à sa mort en 1519, avec ses ateliers reconstitués et un parc où ses machines sont exposées en grand format.",
    summaryEn:
      "Leonardo da Vinci's last home, where he lived from 1516 until his death in 1519, with his reconstructed workshops and a park displaying full-size models of his machines.",
  },
  {
    key: "chateau-amboise",
    name: "Château royal d'Amboise",
    nameEn: "Royal Château of Amboise",
    category: "chateaux",
    commune: "Amboise",
    lat: 47.4136291,
    lng: 0.9859719,
    driveKm: 84,
    driveMin: 62,
    website: "https://www.chateau-amboise.com/",
    summary:
      "Résidence des rois Charles VIII et François Ier dominant la Loire, où la chapelle Saint-Hubert abrite la sépulture de Léonard de Vinci.",
    summaryEn:
      "Residence of kings Charles VIII and François I above the Loire, where the Saint-Hubert chapel holds the tomb of Leonardo da Vinci.",
  },
  {
    key: "montpoupon",
    name: "Château de Montpoupon",
    category: "chateaux",
    commune: "Céré-la-Ronde",
    lat: 47.2530219,
    lng: 1.1412452,
    driveKm: 64,
    driveMin: 52,
    website: "https://www.montpoupon.com/",
    summary:
      "Château habité entre Montrichard et Loches, visité avec ses cuisines et ses communs, qui abritent un musée consacré à la vénerie.",
    summaryEn:
      "Lived-in château between Montrichard and Loches, visited with its kitchens and outbuildings, which house a museum devoted to hunting with hounds.",
  },
  {
    key: "chateau-montresor",
    name: "Château de Montrésor",
    category: "chateaux",
    commune: "Montrésor",
    lat: 47.1557428,
    lng: 1.201239,
    driveKm: 65,
    driveMin: 60,
    website: "https://chateaudemontresor.com/",
    summary:
      "Château meublé dominant l'Indrois, au cœur d'un village classé parmi les Plus Beaux Villages de France, avec une balade aménagée le long de la rivière.",
    summaryEn:
      "Furnished château above the river Indrois, in a village listed among the Plus Beaux Villages de France, with a riverside walk below.",
  },
  {
    key: "loches",
    name: "Cité royale de Loches",
    nameEn: "Royal City of Loches",
    category: "chateaux",
    commune: "Loches",
    lat: 47.1276632,
    lng: 0.9989068,
    driveKm: 90,
    driveMin: 67,
    website: "https://citeroyaleloches.fr/",
    summary:
      "Cité médiévale fortifiée réunissant un donjon du XIe siècle et un logis royal, au-dessus de la vieille ville de Loches.",
    summaryEn:
      "Fortified medieval citadel combining an 11th-century keep and a royal lodge, above the old town of Loches.",
  },
  {
    key: "beauregard",
    name: "Château de Beauregard",
    category: "chateaux",
    commune: "Cellettes",
    lat: 47.5369371,
    lng: 1.3841469,
    driveKm: 36,
    driveMin: 40,
    website: "https://beauregard-loire.com/",
    summary:
      "Château aux portes de Blois connu pour sa galerie des Illustres, qui réunit 327 portraits de personnages historiques, et pour son parc paysager.",
    summaryEn:
      "Château on the edge of Blois known for its Gallery of Illustrious People, with 327 portraits of historical figures, and for its landscaped park.",
  },
  {
    key: "troussay",
    name: "Château de Troussay",
    category: "chateaux",
    commune: "Cheverny",
    lat: 47.491377,
    lng: 1.4245191,
    driveKm: 32,
    driveMin: 32,
    website: "https://chateaudetroussay.com/",
    summary:
      "Petit château Renaissance habité, à quelques minutes de celui de Cheverny, visité avec ses communs et son parc.",
    summaryEn:
      "Small lived-in Renaissance château a few minutes from Cheverny, visited with its outbuildings and park.",
  },
  {
    key: "talcy",
    name: "Château de Talcy",
    category: "chateaux",
    commune: "Talcy",
    lat: 47.769422,
    lng: 1.4445631,
    driveKm: 72,
    driveMin: 65,
    website: "https://www.chateau-talcy.fr/",
    summary:
      "Château de la Beauce géré par le Centre des monuments nationaux, resté meublé, avec colombier, pressoir et verger conservatoire.",
    summaryEn:
      "Château on the Beauce plain run by the Centre des monuments nationaux, still furnished, with a dovecote, a wine press and a heritage orchard.",
  },
  {
    key: "meung-sur-loire",
    name: "Château de Meung-sur-Loire",
    category: "chateaux",
    commune: "Meung-sur-Loire",
    lat: 47.8232517,
    lng: 1.6944827,
    driveKm: 57,
    driveMin: 66,
    website: "https://chateau-de-meung.com/",
    summary:
      "Ancienne résidence des évêques d'Orléans au bord de la Loire, visitée des greniers aux souterrains, avec un parc.",
    summaryEn:
      "Former residence of the bishops of Orléans beside the Loire, visited from the attics down to the underground passages, with a park.",
  },
  {
    key: "maison-de-la-magie",
    name: "Maison de la Magie Robert-Houdin",
    nameEn: "Robert-Houdin House of Magic",
    category: "famille",
    commune: "Blois",
    lat: 47.5864318,
    lng: 1.3331262,
    driveKm: 46,
    driveMin: 47,
    website: "https://www.maisondelamagie.fr/",
    summary:
      "Musée de la magie face au château de Blois, dédié à l'illusionniste blésois Robert-Houdin, avec spectacle et dragons qui sortent des fenêtres.",
    summaryEn:
      "Museum of magic facing the Château of Blois, dedicated to the Blois-born illusionist Robert-Houdin, with a live show and dragons leaning out of the windows.",
  },
  {
    key: "aquarium-de-touraine",
    name: "Aquarium de Touraine",
    nameEn: "Touraine Aquarium",
    category: "famille",
    commune: "Lussault-sur-Loire",
    lat: 47.3879359,
    lng: 0.9114555,
    driveKm: 86,
    driveMin: 66,
    website: "https://www.aquariumdetouraine.com/",
    summary:
      "Aquarium situé entre Amboise et Tours, consacré aux poissons d'eau douce et de mer, sur le parcours de la Loire à Vélo.",
    summaryEn:
      "Aquarium between Amboise and Tours, devoted to freshwater and sea fish, on the Loire à Vélo cycle route.",
  },
  {
    key: "domaine-du-ciran",
    name: "Domaine du Ciran",
    category: "nature",
    commune: "Ménestreau-en-Villette",
    lat: 47.7259468,
    lng: 2.0146503,
    driveKm: 56,
    driveMin: 62,
    website: "https://www.domaineduciran.com/",
    summary:
      "Domaine solognot de 300 hectares ouvert à la promenade, avec parcours de découverte, cerfs, ânes et moutons, aire de jeux et pique-nique.",
    summaryEn:
      "A 300-hectare Sologne estate open for walks, with discovery trails, deer, donkeys and sheep, a playground and picnic areas.",
  },
  {
    key: "marais-de-bourges",
    name: "Marais de Bourges",
    nameEn: "Bourges marshes",
    category: "nature",
    commune: "Bourges",
    lat: 47.0894549,
    lng: 2.4117071,
    driveKm: 75,
    driveMin: 59,
    website: "https://www.bourgesberrytourisme.com/",
    summary:
      "Jardins maraîchers quadrillés de canaux, à quelques minutes à pied de la cathédrale de Bourges, parcourus par des sentiers au bord de l'eau.",
    summaryEn:
      "Market gardens criss-crossed by canals, a few minutes' walk from Bourges cathedral, with footpaths along the water.",
  },
  {
    key: "saint-aignan",
    name: "Saint-Aignan",
    category: "villages",
    commune: "Saint-Aignan",
    lat: 47.269172,
    lng: 1.3760314,
    driveKm: 44,
    driveMin: 33,
    website: "https://www.ville-staignan.fr/",
    summary:
      "Cité médiévale au bord du Cher, voisine du ZooParc de Beauval, avec sa collégiale romane, sa crypte peinte et la terrasse du château.",
    summaryEn:
      "Medieval town on the Cher next to Beauval Zoo, with its Romanesque collegiate church, painted crypt and château terrace.",
  },
  {
    key: "montrichard",
    name: "Montrichard",
    category: "villages",
    commune: "Montrichard Val de Cher",
    lat: 47.3436615,
    lng: 1.1861868,
    driveKm: 54,
    driveMin: 40,
    website: "https://www.montrichardvaldecher.com/",
    summary:
      "Petite ville de la vallée du Cher dominée par son donjon médiéval, avec maisons anciennes et plage aménagée sur la rivière en été.",
    summaryEn:
      "Small town in the Cher valley beneath its medieval keep, with old houses and a river beach in summer.",
  },
  {
    key: "bracieux",
    name: "Bracieux",
    category: "villages",
    commune: "Bracieux",
    lat: 47.5487632,
    lng: 1.5420807,
    driveKm: 32,
    driveMin: 31,
    website: "https://www.bracieux.fr/",
    summary:
      "Bourg au bord du Beuvron, aux portes du domaine de Chambord, organisé autour de sa vieille halle en bois où se tient le marché.",
    summaryEn:
      "Village on the Beuvron at the gates of the Chambord estate, built around its old timber market hall.",
  },
  {
    key: "chaumont-sur-tharonne",
    name: "Chaumont-sur-Tharonne",
    category: "villages",
    commune: "Chaumont-sur-Tharonne",
    lat: 47.6109579,
    lng: 1.9047508,
    driveKm: 33,
    driveMin: 34,
    website: "https://chaumont-sur-tharonne.fr/",
    summary:
      "Village solognot bâti en rond sur une butte, ses maisons de brique serrées autour de l'église.",
    summaryEn:
      "Sologne village built in a ring on a mound, its brick houses gathered around the church.",
  },
  {
    key: "lamotte-beuvron",
    name: "Lamotte-Beuvron",
    category: "villages",
    commune: "Lamotte-Beuvron",
    lat: 47.6016225,
    lng: 2.0253692,
    driveKm: 40,
    driveMin: 41,
    website: "https://www.lamotte-beuvron.fr/",
    summary:
      "Bourg solognot où les sœurs Tatin ont créé la tarte qui porte leur nom, traversé par le canal de la Sauldre et voisin du Parc équestre fédéral.",
    summaryEn:
      "Sologne town where the Tatin sisters created the tart that bears their name, crossed by the Sauldre canal and next to the Federal Equestrian Park.",
  },
  {
    key: "nancay",
    name: "Nançay",
    category: "villages",
    commune: "Nançay",
    lat: 47.3478225,
    lng: 2.1992983,
    driveKm: 40,
    driveMin: 41,
    website: "https://www.berrysolognetourisme.com/",
    summary:
      "Village de la Sologne berrichonne connu pour ses sablés et pour la galerie d'art contemporain Capazza, à côté du Pôle des Étoiles.",
    summaryEn:
      "Village in the Berry side of the Sologne known for its shortbread biscuits and the Capazza contemporary art gallery, next to the Pôle des Étoiles.",
  },
  {
    key: "vierzon",
    name: "Vierzon",
    category: "villages",
    commune: "Vierzon",
    lat: 47.2249364,
    lng: 2.0603909,
    driveKm: 36,
    driveMin: 28,
    website: "https://www.ville-vierzon.fr/",
    summary:
      "Ville du Cher au confluent du Cher et de l'Yèvre, avec son musée installé dans une ancienne usine et le canal de Berry.",
    summaryEn:
      "Town in the Cher department where the Cher and the Yèvre meet, with a museum housed in a former factory and the Berry canal.",
  },
  {
    key: "bourges",
    name: "Bourges, cathédrale et vieille ville",
    nameEn: "Bourges, cathedral and old town",
    category: "villages",
    commune: "Bourges",
    lat: 47.0822328,
    lng: 2.3991788,
    driveKm: 73,
    driveMin: 52,
    website: "https://www.bourges-cathedrale.fr/",
    summary:
      "Cathédrale gothique Saint-Étienne inscrite au patrimoine mondial de l'UNESCO, entourée de rues à maisons à pans de bois et du palais Jacques-Cœur.",
    summaryEn:
      "Gothic Saint-Étienne cathedral, a UNESCO World Heritage site, surrounded by streets of half-timbered houses and the Jacques-Cœur palace.",
  },
  {
    key: "beaugency",
    name: "Beaugency",
    category: "villages",
    commune: "Beaugency",
    lat: 47.7775985,
    lng: 1.6348411,
    driveKm: 50,
    driveMin: 55,
    website: "https://beaugency.fr/",
    summary:
      "Cité médiévale du Loiret au bord de la Loire, avec son vieux pont de pierre, son donjon et ses ruelles.",
    summaryEn:
      "Medieval town in the Loiret on the banks of the Loire, with its old stone bridge, keep and narrow streets.",
  },
  {
    key: "aubigny-sur-nere",
    name: "Aubigny-sur-Nère",
    category: "villages",
    commune: "Aubigny-sur-Nère",
    lat: 47.4887837,
    lng: 2.4408156,
    driveKm: 57,
    driveMin: 62,
    website: "https://www.aubigny.net/",
    summary:
      "Cité des Stuarts, donnée à un Écossais au XVe siècle, avec son château et ses maisons à pans de bois ; elle fête chaque été son histoire franco-écossaise.",
    summaryEn:
      "The town of the Stuarts, given to a Scotsman in the 15th century, with its château and half-timbered houses; it celebrates its Franco-Scottish history every summer.",
  },
  {
    key: "orleans",
    name: "Orléans, cathédrale et quais de Loire",
    nameEn: "Orléans, cathedral and Loire quays",
    category: "villages",
    commune: "Orléans",
    lat: 47.9018937,
    lng: 1.9103809,
    driveKm: 87,
    driveMin: 69,
    website: "https://www.tourisme-orleansmetropole.com/",
    summary:
      "Ville de Jeanne d'Arc au bord de la Loire, avec la cathédrale Sainte-Croix, le centre ancien et les quais.",
    summaryEn:
      "Joan of Arc's city on the Loire, with Sainte-Croix cathedral, the old centre and the quays.",
  },
  {
    key: "maison-des-vins-cheverny",
    name: "Maison des vins de Cheverny",
    nameEn: "Cheverny wine house",
    category: "terroir",
    commune: "Cheverny",
    lat: 47.4994195,
    lng: 1.4597504,
    driveKm: 29,
    driveMin: 29,
    website: "https://maisondesvinsdecheverny.fr/",
    summary:
      "Vitrine des appellations Cheverny et Cour-Cheverny à l'entrée du château, pour déguster et acheter les vins des vignerons au même endroit.",
    summaryEn:
      "Showcase for the Cheverny and Cour-Cheverny appellations at the château entrance, to taste and buy the growers' wines in one place.",
    featured: true,
  },
  {
    key: "max-vauche",
    name: "Chocolaterie Max Vauché",
    nameEn: "Max Vauché chocolate factory",
    category: "terroir",
    commune: "Bracieux",
    lat: 47.5506785,
    lng: 1.5390993,
    driveKm: 33,
    driveMin: 32,
    website: "https://www.maxvauche-chocolatier.com/",
    summary:
      "Chocolaterie artisanale de Bracieux, entre Chambord et Cheverny, qui ouvre son atelier à la visite et à la dégustation.",
    summaryEn:
      "Craft chocolate maker in Bracieux, between Chambord and Cheverny, which opens its workshop for tours and tastings.",
  },
  {
    key: "troglo-degusto",
    name: "Troglo Degusto",
    category: "terroir",
    commune: "Montrichard Val de Cher",
    lat: 47.3512305,
    lng: 1.2332621,
    driveKm: 51,
    driveMin: 39,
    website: "https://www.troglodegusto.fr/",
    summary:
      "Visite guidée de galeries troglodytiques creusées dans le tuffeau à Bourré, terminée par une dégustation des vins AOC du Domaine des Tabourelles.",
    summaryEn:
      "Guided tour of cave galleries cut into the tuffeau stone in Bourré, ending with a tasting of AOC wines from Domaine des Tabourelles.",
  },
  {
    key: "cave-des-roches",
    name: "Cave champignonnière des Roches",
    nameEn: "Cave des Roches mushroom caves",
    category: "terroir",
    commune: "Montrichard Val de Cher",
    lat: 47.3512672,
    lng: 1.2234871,
    driveKm: 51,
    driveMin: 39,
    website: "https://www.le-champignon.com/",
    summary:
      "Visite guidée d'environ 1 heure sous terre à Bourré : carrière de tuffeau, champignonnière en activité et ville souterraine sculptée dans la pierre.",
    summaryEn:
      "Guided tour of about 1 hour underground in Bourré: a tuffeau quarry, a working mushroom farm and an underground town carved in the stone.",
  },
  {
    key: "monmousseau",
    name: "Caves Monmousseau",
    nameEn: "Monmousseau cellars",
    category: "terroir",
    commune: "Montrichard Val de Cher",
    lat: 47.3449882,
    lng: 1.1957658,
    driveKm: 54,
    driveMin: 42,
    website: "https://www.monmousseau.com/",
    summary:
      "Maison de vins à fines bulles de Montrichard, dont les caves creusées dans le tuffeau se visitent avant une dégustation.",
    summaryEn:
      "Sparkling wine house in Montrichard, whose cellars cut into the tuffeau stone can be visited before a tasting.",
  },
  {
    key: "milliere-raboton",
    name: "Balades en bateau Millière Raboton",
    nameEn: "Millière Raboton boat trips",
    category: "loire",
    commune: "Chaumont-sur-Loire",
    lat: 47.483861,
    lng: 1.186639,
    driveKm: 53,
    driveMin: 58,
    website: "https://www.milliere-raboton.net/",
    summary:
      "Balades commentées sur la Loire en bateau traditionnel au départ du port de Chaumont-sur-Loire, toute l'année sur réservation : à l'aube, en journée, au crépuscule ou avec pique-nique.",
    summaryEn:
      "Guided trips on the Loire in a traditional boat from the port of Chaumont-sur-Loire, all year round by booking: at dawn, in the daytime, at dusk or with a picnic.",
  },
  {
    key: "observatoire-loire",
    name: "Observatoire Loire, balades en bateau",
    nameEn: "Observatoire Loire boat trips",
    category: "loire",
    commune: "Blois",
    lat: 47.5874128,
    lng: 1.3463719,
    driveKm: 42,
    driveMin: 40,
    website: "https://www.observatoireloire.fr/",
    summary:
      "Balades en bateaux traditionnels au départ du port de la Creusille à Blois, d'avril à novembre selon les conditions de navigation, avec vue sur le pont Jacques-Gabriel et la ville.",
    summaryEn:
      "Trips in traditional boats from the port of La Creusille in Blois, from April to November depending on river conditions, with views of the Jacques-Gabriel bridge and the town.",
    featured: true,
  },
  {
    key: "marins-du-port-de-chambord",
    name: "Les Marins du Port de Chambord",
    category: "loire",
    commune: "Saint-Dyé-sur-Loire",
    lat: 47.6577619,
    lng: 1.4906502,
    driveKm: 46,
    driveMin: 47,
    website: "https://marins-port-chambord.fr/",
    summary:
      "Association de mariniers de Saint-Dyé-sur-Loire, l'ancien port de Chambord : balades en bateaux traditionnels en journée, au crépuscule ou avec pique-nique au bord de l'eau.",
    summaryEn:
      "Boatmen's association in Saint-Dyé-sur-Loire, the former port of Chambord: trips in traditional boats in the daytime, at dusk or with a riverside picnic.",
  },
  {
    key: "la-rabouilleuse",
    name: "La Rabouilleuse, École de Loire",
    category: "loire",
    commune: "Rochecorbon",
    lat: 47.4083925,
    lng: 0.7574203,
    driveKm: 105,
    driveMin: 71,
    website: "https://www.larabouilleuse-ecoledeloire.com/",
    summary:
      "Navigation à la voile sur des toues de Loire au départ de Rochecorbon, près de Vouvray : balades de 1 h 30 en journée ou de 2 h 30 à l'aube et au crépuscule.",
    summaryEn:
      "Sailing on traditional Loire toue boats from Rochecorbon, near Vouvray: 1 hour 30 trips in the daytime or 2 hour 30 trips at dawn and dusk.",
  },
  {
    key: "passeurs-de-loire",
    name: "Passeurs de Loire",
    category: "loire",
    commune: "Sigloy",
    lat: 47.8336072,
    lng: 2.2337921,
    driveKm: 75,
    driveMin: 82,
    website: "https://www.passeursdeloire.fr/",
    summary:
      "Balades en bateau traditionnel au départ de Sigloy, en amont d'Orléans : promenade découverte de 1 h 30, sortie pique-nique sur une île ou promenade au crépuscule.",
    summaryEn:
      "Trips in a traditional boat from Sigloy, upstream of Orléans: a 1 hour 30 discovery trip, a picnic outing on an island or a trip at dusk.",
  },
  {
    key: "la-belandre",
    name: "La Bélandre, croisière sous Chenonceau",
    nameEn: "La Bélandre, cruise under Chenonceau",
    category: "loire",
    commune: "Chisseaux",
    lat: 47.3289531,
    lng: 1.0878284,
    driveKm: 62,
    driveMin: 47,
    website: "https://www.labelandre.com/",
    summary:
      "Croisières commentées sur le Cher au départ de l'écluse de Chisseaux, qui passent sous les arches du château de Chenonceau ; croisières repas de juin à octobre.",
    summaryEn:
      "Guided cruises on the Cher from the Chisseaux lock, passing under the arches of the Château de Chenonceau; meal cruises from June to October.",
  },
  {
    key: "canoe-company",
    name: "Canoë Company",
    category: "loire",
    commune: "Civray-de-Touraine",
    lat: 47.3258485,
    lng: 1.0468729,
    driveKm: 65,
    driveMin: 52,
    website: "https://www.canoe-company.fr/",
    summary:
      "Location de canoës sur le Cher pour passer sous les arches de Chenonceau, avec bistrot au bord de l'eau et paniers apéro à emporter à bord.",
    summaryEn:
      "Canoe hire on the Cher to paddle under the arches of Chenonceau, with a riverside bistro and aperitif baskets to take on board.",
  },
  {
    key: "loire-kayak",
    name: "Loire Kayak",
    category: "loire",
    commune: "Vineuil",
    lat: 47.6065013,
    lng: 1.3742719,
    driveKm: 44,
    driveMin: 43,
    website: "https://www.loirekayak.com/",
    summary:
      "Descentes de la Loire en canoë-kayak près de Blois, de la balade d'une heure à la randonnée de plusieurs jours, en saison.",
    summaryEn:
      "Canoe and kayak trips down the Loire near Blois, from a one-hour paddle to a multi-day trip, in season.",
  },
  {
    key: "cave-de-vouvray",
    name: "Cave des Producteurs de Vouvray",
    nameEn: "Vouvray growers' cellar",
    category: "terroir",
    commune: "Vouvray",
    lat: 47.4165773,
    lng: 0.7802733,
    driveKm: 98,
    driveMin: 73,
    website: "https://cavedevouvray.com/",
    summary:
      "Cave coopérative de l'appellation Vouvray, creusée dans le tuffeau : visite des galeries et dégustation des vins de chenin, tranquilles et à fines bulles.",
    summaryEn:
      "Cooperative cellar of the Vouvray appellation, cut into the tuffeau stone: a tour of the galleries and a tasting of still and sparkling Chenin wines.",
  },
  {
    key: "maison-laudacius",
    name: "Maison Laudacius",
    category: "terroir",
    commune: "Montlouis-sur-Loire",
    lat: 47.3911089,
    lng: 0.8548607,
    driveKm: 89,
    driveMin: 65,
    website: "https://maison-laudacius.com/",
    summary:
      "Cave des vignerons de Montlouis-sur-Loire, sur la rive gauche de la Loire face à Vouvray : visite, dégustation et vente des vins de l'appellation.",
    summaryEn:
      "Growers' cellar in Montlouis-sur-Loire, on the left bank of the Loire facing Vouvray: tours, tastings and sales of the appellation's wines.",
  },
  {
    key: "quincy",
    name: "Vignoble de Quincy",
    nameEn: "Quincy vineyards",
    category: "terroir",
    commune: "Quincy",
    lat: 47.133365,
    lng: 2.1574605,
    driveKm: 53,
    driveMin: 44,
    website: "https://www.vins-centre-loire.com/fr/",
    summary:
      "Village viticole du Berry, au bord du Cher : son vin blanc de sauvignon a été la première appellation d'origine contrôlée du Val de Loire, reconnue en 1936.",
    summaryEn:
      "Wine village in Berry, on the Cher: its Sauvignon white was the first controlled appellation of the Loire Valley, recognised in 1936.",
  },
  {
    key: "reuilly",
    name: "Vignoble de Reuilly",
    nameEn: "Reuilly vineyards",
    category: "terroir",
    commune: "Reuilly",
    lat: 47.0851206,
    lng: 2.0434337,
    driveKm: 55,
    driveMin: 44,
    website: "https://www.reuilly.fr/",
    summary:
      "Bourg viticole du Berry, dans l'Indre, dont l'appellation produit des blancs de sauvignon, des rouges de pinot noir et des rosés de pinot gris.",
    summaryEn:
      "Wine town in Berry, in the Indre, whose appellation makes Sauvignon whites, Pinot Noir reds and Pinot Gris rosés.",
  },
  {
    key: "menetou-salon",
    name: "Château de Menetou-Salon",
    category: "terroir",
    commune: "Menetou-Salon",
    lat: 47.234838,
    lng: 2.4913375,
    driveKm: 72,
    driveMin: 66,
    website: "https://chateau-menetou-salon.com/",
    summary:
      "Château et domaine viticole au cœur de l'appellation Menetou-Salon, au nord de Bourges.",
    summaryEn:
      "Château and wine estate in the heart of the Menetou-Salon appellation, north of Bourges.",
  },
  {
    key: "villandry",
    name: "Château et jardins de Villandry",
    nameEn: "Château and gardens of Villandry",
    category: "chateaux",
    commune: "Villandry",
    lat: 47.3405655,
    lng: 0.5146063,
    driveKm: 110,
    driveMin: 70,
    website: "https://www.chateauvillandry.fr/",
    summary:
      "Château Renaissance à l'ouest de Tours, visité surtout pour ses jardins en terrasses : potager décoratif, jardin d'ornement et jardin d'eau.",
    summaryEn:
      "Renaissance château west of Tours, visited above all for its terraced gardens: decorative kitchen garden, ornamental garden and water garden.",
  },
  {
    key: "azay-le-rideau",
    name: "Château d'Azay-le-Rideau",
    category: "chateaux",
    commune: "Azay-le-Rideau",
    lat: 47.2590498,
    lng: 0.4657563,
    driveKm: 109,
    driveMin: 71,
    website: "https://www.azay-le-rideau.fr/",
    summary:
      "Château de la Renaissance bâti sur une île de l'Indre, dont les façades se reflètent dans l'eau, géré par le Centre des monuments nationaux.",
    summaryEn:
      "Renaissance château built on an island in the Indre, its façades mirrored in the water, run by the Centre des monuments nationaux.",
  },
  {
    key: "sully-sur-loire",
    name: "Château de Sully-sur-Loire",
    category: "chateaux",
    commune: "Sully-sur-Loire",
    lat: 47.7676531,
    lng: 2.3755601,
    driveKm: 74,
    driveMin: 78,
    website: "https://www.chateausully.fr/",
    summary:
      "Forteresse médiévale entourée de douves en eau, au bord de la Loire, qui fut la demeure du duc de Sully, ministre d'Henri IV.",
    summaryEn:
      "Medieval fortress ringed by a water-filled moat beside the Loire, once the home of the Duke of Sully, minister to Henri IV.",
  },
  {
    key: "bouges",
    name: "Château de Bouges",
    category: "chateaux",
    commune: "Bouges-le-Château",
    lat: 47.042411,
    lng: 1.672947,
    driveKm: 46,
    driveMin: 50,
    website: "https://www.chateau-bouges.fr/",
    summary:
      "Château du XVIIIe siècle dans le Berry, meublé, avec écuries, parc et jardins, géré par le Centre des monuments nationaux.",
    summaryEn:
      "18th-century château in Berry, furnished, with stables, a park and gardens, run by the Centre des monuments nationaux.",
  },
  {
    key: "chateau-de-gien",
    name: "Château-musée de Gien",
    nameEn: "Gien château museum",
    category: "chateaux",
    commune: "Gien",
    lat: 47.6847521,
    lng: 2.6315871,
    driveKm: 85,
    driveMin: 88,
    website: "https://www.chateaumuseegien.fr/",
    summary:
      "Château de brique dominant la Loire, qui abrite un musée consacré à la chasse, à l'histoire et à la nature en Val de Loire, dans la ville de la faïencerie de Gien.",
    summaryEn:
      "Brick château above the Loire, housing a museum devoted to hunting, history and nature in the Loire Valley, in the town of the Gien earthenware factory.",
  },
  {
    key: "pagode-de-chanteloup",
    name: "Pagode de Chanteloup",
    nameEn: "Chanteloup Pagoda",
    category: "chateaux",
    commune: "Amboise",
    lat: 47.391112,
    lng: 0.9701246,
    driveKm: 82,
    driveMin: 58,
    website: "https://www.pagode-chanteloup.com/",
    summary:
      "Pagode du XVIIIe siècle haute de 44 mètres, seul vestige du château du duc de Choiseul, dans un parc avec pièce d'eau à la sortie d'Amboise.",
    summaryEn:
      "An 18th-century pagoda 44 metres high, the only remnant of the Duke of Choiseul's château, in a park with a lake on the edge of Amboise.",
  },
  {
    key: "mini-chateaux",
    name: "Parc Mini-Châteaux",
    nameEn: "Mini-Châteaux park",
    category: "famille",
    commune: "Amboise",
    lat: 47.3922581,
    lng: 1.0025816,
    driveKm: 71,
    driveMin: 58,
    website: "https://www.parcminichateaux.com/",
    summary:
      "Parc de loisirs d'Amboise qui réunit les maquettes des châteaux de la Loire, à parcourir à pied avec des enfants.",
    summaryEn:
      "Leisure park in Amboise bringing together scale models of the Loire châteaux, to walk around with children.",
  },
  {
    key: "reserve-de-beaumarchais",
    name: "Réserve de Beaumarchais",
    nameEn: "Beaumarchais reserve",
    category: "famille",
    commune: "Autrèche",
    lat: 47.5248575,
    lng: 0.9839586,
    driveKm: 80,
    driveMin: 67,
    website: "https://www.reserve-de-beaumarchais.com/",
    summary:
      "Élevage de grands gibiers au nord d'Amboise, visité à bord d'un safari-train qui circule au milieu des animaux.",
    summaryEn:
      "Game farm north of Amboise, visited aboard a safari train that runs among the animals.",
  },
  {
    key: "maison-de-la-bd",
    name: "Maison de la BD",
    nameEn: "Comic strip house (Maison de la BD)",
    category: "famille",
    commune: "Blois",
    lat: 47.584726,
    lng: 1.3332505,
    driveKm: 44,
    driveMin: 43,
    website: "https://www.maisondelabd.com/",
    summary:
      "Lieu d'expositions consacré à la bande dessinée dans le centre de Blois, animé par l'association du festival bd BOUM.",
    summaryEn:
      "Exhibition venue devoted to comics in the centre of Blois, run by the association behind the bd BOUM festival.",
  },
  {
    key: "fondation-du-doute",
    name: "Fondation du doute",
    category: "famille",
    commune: "Blois",
    lat: 47.5892168,
    lng: 1.3290295,
    driveKm: 46,
    driveMin: 45,
    website: "https://www.fondationdudoute.fr/",
    summary:
      "Musée d'art contemporain de Blois consacré au mouvement Fluxus, créé avec l'artiste Ben.",
    summaryEn:
      "Contemporary art museum in Blois devoted to the Fluxus movement, created with the artist Ben.",
  },
  {
    key: "parc-floral-de-la-source",
    name: "Parc floral de la Source",
    nameEn: "La Source floral park",
    category: "nature",
    commune: "Orléans",
    lat: 47.8497252,
    lng: 1.9387789,
    driveKm: 81,
    driveMin: 63,
    website: "https://www.parcfloraldelasource.com/",
    summary:
      "Grand parc paysager d'Orléans où jaillit la source du Loiret, avec jardins thématiques, serre aux papillons et jeux pour enfants.",
    summaryEn:
      "Large landscaped park in Orléans where the source of the Loiret rises, with themed gardens, a butterfly house and play areas.",
  },
  {
    key: "tours",
    name: "Tours, cathédrale et vieux Tours",
    nameEn: "Tours, cathedral and old town",
    category: "villages",
    commune: "Tours",
    lat: 47.3911035,
    lng: 0.6809499,
    driveKm: 103,
    driveMin: 72,
    website: "https://www.tours-tourisme.fr/",
    summary:
      "Capitale de la Touraine au bord de la Loire, avec la cathédrale Saint-Gatien et les maisons à pans de bois de la place Plumereau.",
    summaryEn:
      "Capital of Touraine on the Loire, with Saint-Gatien cathedral and the half-timbered houses of place Plumereau.",
  },
  {
    key: "vendome",
    name: "Vendôme",
    category: "villages",
    commune: "Vendôme",
    lat: 47.7934453,
    lng: 1.0662256,
    driveKm: 76,
    driveMin: 70,
    website: "https://www.vendome-tourisme.fr/",
    summary:
      "Ville du nord du Loir-et-Cher traversée par les bras du Loir, avec l'abbaye de la Trinité et les ruines du château au-dessus des toits.",
    summaryEn:
      "Town in the north of Loir-et-Cher threaded by branches of the Loir, with the Trinité abbey and the château ruins above the rooftops.",
  },
  {
    key: "chedigny",
    name: "Chédigny, village-jardin",
    nameEn: "Chédigny, garden village",
    category: "villages",
    commune: "Chédigny",
    lat: 47.2096349,
    lng: 0.9989134,
    driveKm: 77,
    driveMin: 56,
    website: "https://www.chedigny.fr/fr/",
    summary:
      "Village de Touraine dont les rues sont plantées de rosiers et de vivaces, labellisé Jardin remarquable.",
    summaryEn:
      "Village in Touraine whose streets are planted with roses and perennials, awarded the Jardin remarquable label.",
  },
  {
    key: "clery-saint-andre",
    name: "Basilique de Cléry-Saint-André",
    nameEn: "Basilica of Cléry-Saint-André",
    category: "villages",
    commune: "Cléry-Saint-André",
    lat: 47.820139,
    lng: 1.755292,
    driveKm: 57,
    driveMin: 62,
    website: "https://www.clery-saint-andre.com/",
    summary:
      "Basilique gothique Notre-Dame de Cléry, près de la Loire, où le roi Louis XI a choisi d'être enterré.",
    summaryEn:
      "Gothic basilica of Notre-Dame de Cléry, near the Loire, where King Louis XI chose to be buried.",
  },
  {
    key: "saint-benoit-sur-loire",
    name: "Abbaye de Fleury",
    nameEn: "Fleury Abbey",
    category: "villages",
    commune: "Saint-Benoît-sur-Loire",
    lat: 47.8098365,
    lng: 2.3051494,
    driveKm: 82,
    driveMin: 87,
    website: "https://www.abbaye-fleury.com/",
    summary:
      "Abbaye bénédictine de Saint-Benoît-sur-Loire, toujours habitée par des moines, dont la basilique romane abrite les reliques de saint Benoît.",
    summaryEn:
      "Benedictine abbey in Saint-Benoît-sur-Loire, still home to monks, whose Romanesque basilica holds the relics of Saint Benedict.",
  },
  {
    key: "issoudun",
    name: "Issoudun",
    category: "villages",
    commune: "Issoudun",
    lat: 46.9478025,
    lng: 1.9897998,
    driveKm: 71,
    driveMin: 63,
    website: "https://www.issoudun.fr/",
    summary:
      "Ville du Berry dominée par la Tour Blanche, donjon médiéval, avec le musée de l'Hospice Saint-Roch.",
    summaryEn:
      "Town in Berry beneath the Tour Blanche, a medieval keep, with the Hospice Saint-Roch museum.",
  },
  {
    key: "mehun-sur-yevre",
    name: "Mehun-sur-Yèvre",
    category: "villages",
    commune: "Mehun-sur-Yèvre",
    lat: 47.1426566,
    lng: 2.2166469,
    driveKm: 52,
    driveMin: 42,
    website: "https://www.ville-mehun-sur-yevre.fr/",
    summary:
      "Petite ville du Cher où subsistent les tours du château de Charles VII, qui y mourut en 1461, connue aussi pour sa porcelaine.",
    summaryEn:
      "Small town in the Cher department where the towers of Charles VII's château still stand (he died here in 1461), also known for its porcelain.",
  },
  {
    key: "nohant",
    name: "Maison de George Sand à Nohant",
    nameEn: "George Sand's house in Nohant",
    category: "villages",
    commune: "Nohant-Vic",
    lat: 46.6250145,
    lng: 1.9753144,
    driveKm: 122,
    driveMin: 88,
    website: "https://www.maison-george-sand.fr/",
    summary:
      "Maison de l'écrivaine George Sand dans le Berry, restée meublée, avec son jardin, ouverte en visite guidée par le Centre des monuments nationaux.",
    summaryEn:
      "Home of the writer George Sand in Berry, still furnished, with its garden, open for guided tours through the Centre des monuments nationaux.",
  },
  {
    key: "site-de-baltan",
    name: "Site de Baltan",
    nameEn: "Baltan nature site",
    category: "nature",
    commune: "Villeherviers",
    lat: 47.3612972,
    lng: 1.8004009,
    driveKm: 5,
    driveMin: 6,
    website: "https://www.sologne-tourisme.fr/tourinsoft/site-de-baltan/",
    summary:
      "Espace naturel sensible au bord de la Sauldre, gratuit et ouvert toute l'année : parcours de 1,3 km ponctué de 6 bornes pédagogiques, aire de pique-nique et ponton de pêche.",
    summaryEn:
      "Protected natural site on the banks of the Sauldre, free and open all year: a 1.3 km trail with 6 information posts, a picnic area and a fishing pontoon.",
  },
  {
    key: "etang-de-malzone",
    name: "Réserve de l'étang de Malzoné",
    nameEn: "Malzoné pond reserve",
    category: "nature",
    commune: "Millançay",
    lat: 47.49173,
    lng: 1.80869,
    driveKm: 17,
    driveMin: 18,
    website: "https://fdc41.com/animation-nature/reserve-de-malzone/",
    summary:
      "Réserve de chasse et de faune sauvage de 77 ha, dont 32 d'eau, où toute chasse est interdite : 2 observatoires et un sentier ouvert toute l'année, gratuit.",
    summaryEn:
      "Wildlife reserve of 77 hectares, 32 of them water, where all hunting is banned: 2 bird hides and a footpath open all year, free of charge.",
  },
  {
    key: "la-ferte-imbault",
    name: "La Ferté-Imbault, château et village",
    nameEn: "La Ferté-Imbault, château and village",
    category: "villages",
    commune: "La Ferté-Imbault",
    lat: 47.38589,
    lng: 1.95921,
    driveKm: 17,
    driveMin: 19,
    website:
      "https://www.sologne-tourisme.fr/experiences/le-chateau-de-la-ferte-imbault/",
    summary:
      "Village de Sologne dominé par un château de brique entouré de douves, ouvert à la visite.",
    summaryEn:
      "Sologne village overlooked by a moated brick château that is open to visitors.",
  },
  {
    key: "etang-le-mouet",
    name: "Étang le Mouet",
    nameEn: "Le Mouet pond",
    category: "nature",
    commune: "Saint-Viâtre",
    lat: 47.46594,
    lng: 1.95063,
    driveKm: 22,
    driveMin: 28,
    website: "https://www.sologne-tourisme.fr/tourinsoft/etang-le-mouet/",
    summary:
      "Plan d'eau dont un sentier aménagé de 1,5 km fait le tour, avec un observatoire ouvert toute l'année, des tables de pique-nique et des panneaux pédagogiques.",
    summaryEn:
      "Pond circled by a 1.5 km laid-out path, with a bird hide open all year, picnic tables and information boards.",
  },
  {
    key: "saint-viatre",
    name: "Saint-Viâtre, village et église",
    nameEn: "Saint-Viâtre, village and church",
    category: "villages",
    commune: "Saint-Viâtre",
    lat: 47.5231667,
    lng: 1.9335241,
    driveKm: 24,
    driveMin: 29,
    website: "https://www.saint-viatre.fr/leglise/",
    summary:
      "Village des étangs de Sologne : une église au clocher tors, dont la crypte date sans doute du XIe siècle, et le Chafaud, petit monument de brique du XVe siècle.",
    summaryEn:
      "Village among the Sologne ponds: a church with a twisted spire and a crypt probably dating from the 11th century, and the Chafaud, a small 15th-century brick monument.",
  },
  {
    key: "montgolfiere-au-gre-des-vents",
    name: "Au Gré des Vents, vols en montgolfière",
    nameEn: "Au Gré des Vents hot-air balloon flights",
    category: "chateaux",
    commune: "Le Controis-en-Sologne",
    lat: 47.4307204,
    lng: 1.4319844,
    driveKm: 27,
    driveMin: 29,
    website: "https://au-gre-des-vents.net/",
    summary:
      "Compagnie de montgolfières dont le bureau de Contres sert de point de rendez-vous fixe, pour des vols au-dessus du pays des châteaux de la Loire.",
    summaryEn:
      "Hot-air balloon company whose office in Contres is a fixed meeting point for flights over the Loire château country.",
  },
  {
    key: "etang-de-beaumont",
    name: "Étang de Beaumont",
    nameEn: "Beaumont pond",
    category: "nature",
    commune: "Neung-sur-Beuvron",
    lat: 47.54924,
    lng: 1.7635,
    driveKm: 27,
    driveMin: 32,
    website:
      "https://www.cen-centrevaldeloire.org/les-actions-du-conservatoire/le-reseau-de-sites-preserves/les-sites-du-loir-et-cher/letang-de-beaumont/",
    summary:
      "Étang de 35,73 ha préservé par le Conservatoire d'espaces naturels Centre-Val de Loire, avec un observatoire libre d'accès toute l'année, aménagé pour les personnes à mobilité réduite.",
    summaryEn:
      "Pond of 35.73 hectares protected by the regional nature conservancy, with a bird hide open freely all year and adapted for visitors with reduced mobility.",
  },
  {
    key: "velos-des-chateaux",
    name: "Vélos des Châteaux, location de vélos",
    nameEn: "Vélos des Châteaux bike hire",
    category: "pratique",
    commune: "Bracieux",
    lat: 47.553417,
    lng: 1.53375,
    driveKm: 33,
    driveMin: 32,
    website: "https://velosdeschateaux.com/",
    summary:
      "Loueur de vélos labellisé Accueil Vélo : vélos classiques et électriques, tandems, sièges et remorques pour enfants, livraison possible à un point de rendez-vous.",
    summaryEn:
      "Bike hire shop with the Accueil Vélo label: standard and electric bikes, tandems, child seats and trailers, with delivery to a meeting point on request.",
  },
  {
    key: "ecurie-de-la-coliniere",
    name: "Écurie de la Colinière",
    nameEn: "Écurie de la Colinière riding stables",
    category: "equestre",
    commune: "Cheverny",
    lat: 47.493716,
    lng: 1.419528,
    driveKm: 32,
    driveMin: 34,
    website: "https://www.ecurie-de-la-coliniere.com/",
    summary:
      "Écurie qui publie ses tarifs et propose des balades à cheval et, pour les plus petits, du poney en main, à 2 min du château de Troussay.",
    summaryEn:
      "Riding stables with published prices, offering hacks on horseback and led pony rides for small children, 2 min from the Château de Troussay.",
  },
  {
    key: "sables-de-nancay",
    name: "Les Sablés de Nançay",
    nameEn: "Les Sablés de Nançay biscuit workshop",
    category: "terroir",
    commune: "Nançay",
    lat: 47.349653,
    lng: 2.1846728,
    driveKm: 39,
    driveMin: 39,
    website: "https://www.lessablesdenancay.com/",
    summary:
      "Boutique d'usine des sablés de Nançay : visite libre et gratuite de l'atelier, avec un film d'une douzaine de minutes et une dégustation.",
    summaryEn:
      "Factory shop of the Nançay shortbread biscuits: a free self-guided visit of the workshop, with a film of about twelve minutes and a tasting.",
  },
  {
    key: "galerie-capazza",
    name: "Galerie Capazza",
    nameEn: "Galerie Capazza art gallery",
    category: "villages",
    commune: "Nançay",
    lat: 47.3478225,
    lng: 2.1992983,
    driveKm: 40,
    driveMin: 41,
    website: "https://www.galerie-capazza.com/fr/",
    summary:
      "Galerie d'art contemporain de 2 000 m² installée dans les anciennes écuries du château de Nançay, ouverte le week-end et les jours fériés.",
    summaryEn:
      "Contemporary art gallery of 2,000 m² in the former stables of the Château de Nançay, open at weekends and on public holidays.",
  },
  {
    key: "maison-tatin",
    name: "La Maison Tatin",
    nameEn: "La Maison Tatin tea room",
    category: "terroir",
    commune: "Lamotte-Beuvron",
    lat: 47.5940762,
    lng: 2.0233097,
    driveKm: 39,
    driveMin: 41,
    website: "https://www.lamaisontatin.fr/",
    summary:
      "Maison du 5 avenue de Vierzon, face à la gare : un salon de thé où l'on sert la tarte Tatin, vendue aussi entière à emporter.",
    summaryEn:
      "House at 5 avenue de Vierzon, opposite the station: a tea room serving tarte Tatin, also sold whole to take away.",
  },
  {
    key: "villa-quincy",
    name: "Villa Quincy",
    nameEn: "Villa Quincy wine centre",
    category: "terroir",
    commune: "Quincy",
    lat: 47.1330773,
    lng: 2.156789,
    driveKm: 53,
    driveMin: 44,
    website: "https://lavillaquincy.wixsite.com/villaquincy",
    summary:
      "Ouverte depuis 2007, la Villa Quincy réunit un musée consacré au sauvignon blanc et une cave qui vend les vins de plus de 30 producteurs de Quincy et de Reuilly.",
    summaryEn:
      "Open since 2007, the Villa Quincy combines a museum about Sauvignon Blanc with a shop selling wines from more than 30 Quincy and Reuilly growers.",
  },
  {
    key: "maison-de-reuilly",
    name: "Maison de Reuilly",
    nameEn: "Maison de Reuilly wine and arts centre",
    category: "terroir",
    commune: "Reuilly",
    lat: 47.0849708,
    lng: 2.0460134,
    driveKm: 55,
    driveMin: 44,
    website: "https://mdr.reuilly.fr/wordpress/",
    summary:
      "Lieu municipal inauguré en juin 2017, consacré à l'art, à la culture et au terroir de Reuilly, avec des salles d'exposition.",
    summaryEn:
      "Municipal venue opened in June 2017, devoted to the art, culture and local produce of Reuilly, with exhibition rooms.",
  },
  {
    key: "golf-des-aisses",
    name: "Les Aisses Golf",
    nameEn: "Les Aisses golf course",
    category: "nature",
    commune: "La Ferté-Saint-Aubin",
    lat: 47.6943621,
    lng: 1.9653349,
    driveKm: 46,
    driveMin: 48,
    website: "https://www.aissesgolf.com/",
    summary:
      "Golf de Sologne avec un 18 trous par 72 de 6 670 m, dessiné par Martin Hawtree, et un 9 trous par 36.",
    summaryEn:
      "Sologne golf club with an 18-hole par-72 course of 6,670 m designed by Martin Hawtree, and a 9-hole par-36 course.",
  },
  {
    key: "caves-du-pere-auguste",
    name: "Caves du Père Auguste",
    nameEn: "Père Auguste cellars",
    category: "terroir",
    commune: "Civray-de-Touraine",
    lat: 47.3347401,
    lng: 1.0493392,
    driveKm: 64,
    driveMin: 50,
    website: "https://www.pereauguste.com/",
    summary:
      "Famille de vignerons installée depuis 1875 en appellation Touraine-Chenonceaux, à 2 km du château de Chenonceau : visite libre des caves et dégustation.",
    summaryEn:
      "Family of winegrowers established since 1875 in the Touraine-Chenonceaux appellation, 2 km from the Château de Chenonceau: self-guided cellar visit and tasting.",
  },
  {
    key: "palais-jacques-coeur",
    name: "Palais Jacques-Cœur",
    nameEn: "Jacques-Cœur Palace",
    category: "villages",
    commune: "Bourges",
    lat: 47.0842142,
    lng: 2.3935463,
    driveKm: 72,
    driveMin: 52,
    website: "https://www.palais-jacques-coeur.fr/",
    summary:
      "Palais de marchand du XVe siècle au centre de Bourges, qui se visite avec un billet jumelé aux parties payantes de la cathédrale.",
    summaryEn:
      "15th-century merchant's palace in the centre of Bourges, visited on a combined ticket with the paying parts of the cathedral.",
  },
  {
    key: "brinon-sur-sauldre",
    name: "Brinon-sur-Sauldre, église et caquetoire",
    nameEn: "Brinon-sur-Sauldre, church and timber porch",
    category: "villages",
    commune: "Brinon-sur-Sauldre",
    lat: 47.5663515,
    lng: 2.255662,
    driveKm: 50,
    driveMin: 54,
    website:
      "https://www.aubigny-sologne.com/jexplore/destination-sauldre-sologne/secrets-de-villages/brinon-sur-sauldre/",
    summary:
      "Village du Cher dont l'église Saint-Barthélemy garde une nef du XIIe siècle, un clocher entièrement en bois et un caquetoire du XVIe siècle.",
    summaryEn:
      "Village in the Cher whose church of Saint-Barthélemy has a 12th-century nave, an all-timber bell tower and a 16th-century caquetoire, a covered timber porch.",
  },
  {
    key: "golf-de-la-carte",
    name: "Golf du Domaine de la Carte",
    nameEn: "Domaine de la Carte golf course",
    category: "nature",
    commune: "Valloire-sur-Cisse",
    lat: 47.501474,
    lng: 1.2283641,
    driveKm: 56,
    driveMin: 58,
    website:
      "https://www.ffgolf.org/parcours-detours/guide-des-golfs/golf-de-la-carte",
    summary:
      "Golf de Chouzy-sur-Cisse, près de Blois : un 9 trous aux allures de links et un compact de 9 trous, ouverts toute l'année.",
    summaryEn:
      "Golf club in Chouzy-sur-Cisse, near Blois: a links-style 9-hole course and a compact 9-hole course, open all year.",
  },
  {
    key: "musee-compagnonnage-tours",
    name: "Musée du Compagnonnage",
    nameEn: "Musée du Compagnonnage (craft guilds museum)",
    category: "villages",
    commune: "Tours",
    lat: 47.3961073,
    lng: 0.686753,
    driveKm: 102,
    driveMin: 69,
    website:
      "https://musees.tours.fr/visiter/musees-et-centre-d-exposition/musee-du-compagnonnage/",
    summary:
      "Musée consacré au compagnonnage, installé au 8 rue Nationale dans l'ancienne abbaye Saint-Julien, fermé le mardi.",
    summaryEn:
      "Museum about the compagnons, France's travelling craft guilds, at 8 rue Nationale in the former Saint-Julien abbey, closed on Tuesdays.",
  },
  {
    key: "halles-de-tours",
    name: "Les Halles de Tours",
    nameEn: "Les Halles de Tours covered market",
    category: "villages",
    commune: "Tours",
    lat: 47.3911035,
    lng: 0.6809499,
    driveKm: 103,
    driveMin: 72,
    website: "https://leshallesdetours.fr/",
    summary:
      "Marché couvert de la place Gaston-Paillhou, ouvert tous les jours, à 7 min à pied de la place Plumereau. Les Halles annoncent 900 places de stationnement.",
    summaryEn:
      "Covered market on place Gaston-Paillhou, open every day, 7 min on foot from place Plumereau. The market advertises 900 parking spaces.",
  },
];
