// Mapping explicite des 19 .webp → métadonnées
export const IMAGE_MAP = [
  {
    filename: "entree-commode-deco-briques.webp",
    altFr: "Entrée du gîte, commode décorée et mur de briques",
    altEn: "Gîte entrance, decorated dresser and brick wall",
    captionFr: "L'entrée, brique et décoration artisanale",
    captionEn: "Entrance, brick and handcrafted decor",
    category: "entree",
    focalX: 50,
    focalY: 42,
  },
  {
    filename: "entree-detail-lampe-vase-briques.webp",
    altFr: "Détail entrée : lampe et vase devant les briques",
    altEn: "Entrance detail: lamp and vase against brick wall",
    captionFr: "Détail entrée, ambiance chaleureuse",
    captionEn: "Entrance detail, warm atmosphere",
    category: "entree",
    focalX: 50,
    focalY: 68,
  },
  {
    filename: "entree-porte-manteau-papier-peint-herons.webp",
    altFr: "Entrée avec porte-manteau et papier peint hérons",
    altEn: "Entrance with coat rack and heron wallpaper",
    captionFr: "Entrée, papier peint hérons",
    captionEn: "Entrance, heron wallpaper",
    category: "entree",
    focalX: 50,
    focalY: 35,
  },
  {
    filename: "chambre-1-lit-double-vert-sauge.webp",
    altFr: "Chambre 1, lit double, tons vert sauge",
    altEn: "Bedroom 1, double bed, sage green tones",
    captionFr: "Chambre 1, lit double vert sauge",
    captionEn: "Bedroom 1, sage green double bed",
    category: "chambre",
    focalX: 50,
    focalY: 45,
  },
  {
    filename: "chambre-1-vue-ensemble-papier-peint-foret.webp",
    altFr: "Chambre 1, vue d'ensemble, papier peint forêt",
    altEn: "Bedroom 1, full view, forest wallpaper",
    captionFr: "Chambre 1, vue d'ensemble",
    captionEn: "Bedroom 1, full view",
    category: "chambre",
    focalX: 60,
    focalY: 45,
  },
  {
    filename: "chambre-2-lit-double-sous-pente-terracotta.webp",
    altFr: "Chambre 2, lit double sous les combles, tons terracotta",
    altEn: "Bedroom 2, double bed under the eaves, terracotta tones",
    captionFr: "Chambre 2, sous pente terracotta",
    captionEn: "Bedroom 2, terracotta sloped ceiling",
    category: "chambre",
    focalX: 45,
    focalY: 50,
  },
  {
    filename: "chambre-2-tete-de-lit-sous-pente.webp",
    altFr: "Chambre 2, tête de lit sous les combles",
    altEn: "Bedroom 2, headboard under the eaves",
    captionFr: "Chambre 2, tête de lit",
    captionEn: "Bedroom 2, headboard",
    category: "chambre",
    focalX: 45,
    focalY: 55,
  },
  {
    filename: "chambre-3-lits-simples-sous-pente.webp",
    altFr: "Chambre 3, lits simples sous les combles",
    altEn: "Bedroom 3, twin beds under the eaves",
    captionFr: "Chambre 3, lits simples",
    captionEn: "Bedroom 3, twin beds",
    category: "chambre",
    focalX: 50,
    focalY: 50,
  },
  {
    filename: "sejour-canape-buffet-escalier.webp",
    altFr: "Séjour, canapé, buffet et escalier",
    altEn: "Living room, sofa, sideboard and staircase",
    captionFr: "Séjour, espace de vie",
    captionEn: "Living room, living space",
    category: "sejour",
    focalX: 50,
    focalY: 42,
  },
  {
    filename: "sejour-canape-tv-escalier.webp",
    altFr: "Séjour, canapé, télévision et escalier",
    altEn: "Living room, sofa, TV and staircase",
    captionFr: "Séjour, coin télévision",
    captionEn: "Living room, TV area",
    category: "sejour",
    focalX: 50,
    focalY: 55,
  },
  {
    filename: "salon-cheminee-canapes-tv.webp",
    altFr: "Salon avec cheminée, canapés et télévision",
    altEn: "Lounge with fireplace, sofas and TV",
    captionFr: "Salon, cheminée et confort",
    captionEn: "Lounge, fireplace and comfort",
    category: "salon",
    focalX: 50,
    focalY: 55,
  },
  {
    filename: "salon-baby-foot-mur-briques.webp",
    altFr: "Salon, baby-foot devant le mur de briques",
    altEn: "Lounge, foosball table against brick wall",
    captionFr: "Salon, baby-foot et briques",
    captionEn: "Lounge, foosball and brick wall",
    category: "salon",
    focalX: 50,
    focalY: 55,
  },
  {
    filename: "cuisine-equipee-verte-poutres.webp",
    altFr: "Cuisine équipée verte avec poutres apparentes",
    altEn: "Fully equipped green kitchen with exposed beams",
    captionFr: "Cuisine, verte et bien équipée",
    captionEn: "Kitchen, green and fully equipped",
    category: "cuisine",
    focalX: 50,
    focalY: 50,
  },
  {
    filename: "detail-deco-coiffeuse-miroir-chambre-1.webp",
    altFr: "Détail décoration, coiffeuse et miroir, chambre 1",
    altEn: "Decor detail, dressing table and mirror, bedroom 1",
    captionFr: "Chambre 1, coiffeuse",
    captionEn: "Bedroom 1, dressing table",
    category: "detail",
    focalX: 45,
    focalY: 55,
  },
  {
    filename: "detail-deco-cuisine-cloche-bronze.webp",
    altFr: "Détail décoration cuisine, cloche en bronze",
    altEn: "Kitchen decor detail, bronze cloche",
    captionFr: "Cuisine, cloche bronze",
    captionEn: "Kitchen, bronze cloche",
    category: "detail",
    focalX: 60,
    focalY: 50,
  },
  {
    filename: "detail-deco-vase-visage-dore.webp",
    altFr: "Détail décoration, vase visage doré",
    altEn: "Decor detail, golden face vase",
    captionFr: "Détail déco, vase doré",
    captionEn: "Decor detail, golden vase",
    category: "detail",
    focalX: 50,
    focalY: 30,
  },
  {
    filename: "jardin-terrasse-vue-ensemble.webp",
    altFr: "Vue d'ensemble du jardin et de la terrasse",
    altEn: "Full view of the garden and terrace",
    captionFr: "Jardin, vue d'ensemble",
    captionEn: "Garden, full view",
    category: "jardin",
    focalX: 50,
    focalY: 45,
  },
  {
    filename: "jardin-souche-arbre-decorative.webp",
    altFr: "Jardin, souche d'arbre décorative",
    altEn: "Garden, decorative tree stump",
    captionFr: "Jardin, détail naturel",
    captionEn: "Garden, natural detail",
    category: "jardin",
    focalX: 55,
    focalY: 45,
  },
  {
    filename: "terrasse-salon-jardin.webp",
    altFr: "Terrasse avec salon de jardin",
    altEn: "Terrace with garden furniture",
    captionFr: "Terrasse, salon extérieur",
    captionEn: "Terrace, outdoor lounge",
    category: "jardin",
    focalX: 50,
    focalY: 55,
  },
] as const;
