/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    places: Place;
    guides: Guide;
    'official-sites': OfficialSite;
    amenities: Amenity;
    testimonials: Testimonial;
    'contact-messages': ContactMessage;
    media: Media;
    users: User;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    places: PlacesSelect<false> | PlacesSelect<true>;
    guides: GuidesSelect<false> | GuidesSelect<true>;
    'official-sites': OfficialSitesSelect<false> | OfficialSitesSelect<true>;
    amenities: AmenitiesSelect<false> | AmenitiesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('fr' | 'en') | ('fr' | 'en')[];
  globals: {
    'home-page': HomePage;
    'cottage-page': CottagePage;
    'surroundings-page': SurroundingsPage;
    'guides-page': GuidesPage;
    'rates-page': RatesPage;
    'contact-page': ContactPage;
    'site-settings': SiteSetting;
    'pricing-config': PricingConfig;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'cottage-page': CottagePageSelect<false> | CottagePageSelect<true>;
    'surroundings-page': SurroundingsPageSelect<false> | SurroundingsPageSelect<true>;
    'guides-page': GuidesPageSelect<false> | GuidesPageSelect<true>;
    'rates-page': RatesPageSelect<false> | RatesPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'pricing-config': PricingConfigSelect<false> | PricingConfigSelect<true>;
  };
  locale: 'fr' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Tout ce qui se visite depuis le gîte : châteaux, sites équestres, sorties en famille, nature. Un lieu peut aussi être cité dans un guide.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "places".
 */
export interface Place {
  id: number;
  /**
   * Le nom officiel, tel qu'il est écrit sur le site du lieu.
   */
  name: string;
  /**
   * Range le lieu sur la page « Les alentours » et lui donne sa couleur sur les cartes.
   */
  category:
    | 'chateaux'
    | 'equestre'
    | 'famille'
    | 'nature'
    | 'villages'
    | 'terroir'
    | 'loire'
    | 'romorantin'
    | 'pratique';
  /**
   * La ville ou le village où se trouve le lieu.
   */
  commune?: string | null;
  /**
   * Ce qu'on y fait ou ce qu'on y voit, en une phrase factuelle. Affichée sur la carte du lieu.
   */
  summary?: string | null;
  /**
   * Une photo du lieu, en largeur. Si elle n'est pas de vous, remplissez le crédit photo.
   */
  image?: (number | null) | Media;
  /**
   * Le nom du lieu ou sa rue, puis la commune. Plus l'adresse est précise, plus la position est juste.
   */
  address?: string | null;
  geocodedAddress?: string | null;
  /**
   * Calculé automatiquement depuis l'adresse.
   */
  driveMin: number;
  /**
   * Calculée automatiquement depuis l'adresse.
   */
  driveKm: number;
  routeMessage?: string | null;
  /**
   * La position nord-sud du lieu. Trouvée automatiquement depuis l'adresse.
   */
  lat: number;
  /**
   * La position est-ouest du lieu : le second nombre donné par Google Maps.
   */
  lng: number;
  /**
   * Cochée, la latitude et la longitude ne sont plus jamais remplacées par le calcul automatique. Le temps de route reste calculé depuis cette position.
   */
  positionLocked?: boolean | null;
  /**
   * Affiché sur la carte du lieu et à la fin des guides qui le citent.
   */
  website?: string | null;
  /**
   * Les événements qui reviennent chaque année sur ce lieu (concours, salons, festivals).
   */
  events?:
    | {
        /**
         * Le nom de l'événement.
         */
        name: string;
        /**
         * Le mois ou la saison, sans année.
         */
        period?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Le lieu défile dans le bandeau des temps de route, en haut de l'accueil et de la page « Les alentours ». Dix lieux au plus.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * Toutes les photos du site. Le site les redimensionne et les allège tout seul.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Décrivez ce qu'on voit, comme à quelqu'un au téléphone. Cette phrase est lue aux personnes malvoyantes et aide Google à comprendre la photo.
   */
  alt: string;
  /**
   * Un court texte affiché sous la photo quand on l'agrandit. Facultatif.
   */
  caption?: string | null;
  /**
   * L'auteur et la licence. À remplir pour toute photo qui n'est pas la vôtre.
   */
  credit?: string | null;
  /**
   * La page où vous avez trouvé la photo.
   */
  creditUrl?: string | null;
  blurDataURL?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    share?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Des articles pratiques pour les voyageurs : châteaux, Beauval, séjours équestres, nature. Ils aident le site à être trouvé sur Google.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides".
 */
export interface Guide {
  id: number;
  /**
   * La question à laquelle le guide répond, avec le nom du lieu. C'est le grand titre de la page.
   */
  title: string;
  /**
   * Deux phrases qui répondent tout de suite à la question du voyageur. Affiché en tête du guide et dans les listes de guides.
   */
  excerpt: string;
  /**
   * Affichée en tête du guide et sur sa carte dans les listes.
   */
  image?: (number | null) | Media;
  /**
   * Découpez le texte avec des titres de niveau 2 : ils forment le sommaire du guide. Le bouton « + » ajoute un programme heure par heure ou un tableau (tarifs, comparatif). Citez les temps de route depuis le gîte.
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Quatre à six lignes que le voyageur cherche en premier : durée, budget, meilleure période, à réserver, stationnement, avec un chien.
   */
  practical?:
    | {
        /**
         * Un ou deux mots.
         */
        label: string;
        /**
         * Une phrase courte, avec un chiffre si possible.
         */
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * La date à laquelle horaires, tarifs et adresses ont été relus sur les sites officiels. Elle s'affiche sur le guide : changez-la seulement après une vraie relecture.
   */
  checkedAt?: string | null;
  /**
   * Les pages officielles où chaque horaire, tarif ou date a été vérifié. Elles s'affichent en fin de guide.
   */
  sources?:
    | {
        /**
         * Le nom du site, puis ce qu'on y a vérifié.
         */
        name: string;
        /**
         * Ouvrez la page et copiez l'adresse affichée en haut du navigateur.
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Ces lieux s'affichent en fin de guide avec leur temps de route depuis le gîte. Le lieu manque ? Ajoutez-le d'abord dans « Lieux aux alentours ».
   */
  places?: (number | Place)[] | null;
  /**
   * Trois à cinq questions courtes. Google peut les reprendre dans ses résultats.
   */
  faq?:
    | {
        /**
         * Une question telle qu'un voyageur la taperait dans Google.
         */
        question: string;
        /**
         * Répondez dès la première phrase, puis précisez en une ou deux phrases.
         */
        answer: string;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * La photo de fond de l'image affichée quand la page est partagée. Laissez vide pour reprendre la photo d'en-tête.
     */
    image?: (number | null) | Media;
    /**
     * Le titre écrit en grand sur l'image qui s'affiche quand la page est partagée sur WhatsApp, Facebook ou par SMS. Quatre à six mots. Pour un guide, laissez vide : le début de son titre est repris.
     */
    shareTitle?: string | null;
  };
  /**
   * Range le guide dans la liste des guides et choisit les sites officiels proposés à la fin.
   */
  theme: 'chateaux' | 'equestre' | 'famille' | 'nature' | 'villages' | 'terroir' | 'loire' | 'romorantin';
  /**
   * Laissez vide : l'adresse se crée toute seule à partir du titre, à la première publication. Si vous la changez ensuite, l'ancienne adresse renvoie toute seule vers la nouvelle.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Offices de tourisme, sites institutionnels et mairies cités en bas de la page « Les alentours », à la fin des guides et dans le pied de page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "official-sites".
 */
export interface OfficialSite {
  id: number;
  /**
   * Le nom affiché comme lien.
   */
  name: string;
  /**
   * Ouvrez le site et copiez l'adresse affichée en haut du navigateur.
   */
  url: string;
  /**
   * Une phrase affichée sous le lien. Inutile pour une mairie.
   */
  detail?: string | null;
  /**
   * La rubrique où le lien apparaît sur « Les alentours ».
   */
  group: 'venir' | 'sologne' | 'chateaux' | 'berry' | 'velo' | 'terroir' | 'mairies';
  /**
   * Les plus petits nombres passent en premier dans leur rubrique.
   */
  order?: number | null;
  /**
   * Cinq sites au plus, pour que la colonne « Sources officielles » reste courte.
   */
  showInFooter?: boolean | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * La liste des équipements affichée sur la page « Le gîte », rangée par catégorie. Elle est aussi transmise à Google.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "amenities".
 */
export interface Amenity {
  id: number;
  /**
   * Un nom court, trois ou quatre mots au plus.
   */
  name: string;
  /**
   * Le petit dessin affiché à côté du nom.
   */
  icon?:
    | (
        | 'wifi'
        | 'parking'
        | 'kitchen'
        | 'dishes'
        | 'fridge'
        | 'coffee'
        | 'barbecue'
        | 'garden'
        | 'fence'
        | 'living'
        | 'tv'
        | 'games'
        | 'bed'
        | 'linen'
        | 'bath'
        | 'laundry'
        | 'heating'
        | 'baby'
        | 'pets'
        | 'bike'
      )
    | null;
  /**
   * Le groupe où l'équipement apparaît sur la page « Le gîte ».
   */
  category: 'indoor' | 'outdoor' | 'kitchen' | 'comfort' | 'bedroom' | 'bathroom' | 'tech';
  /**
   * Décochez pour masquer cet équipement sans le supprimer.
   */
  enabled?: boolean | null;
  /**
   * Les plus petits nombres passent en premier dans leur catégorie. Deux équipements au même nombre sont rangés par ordre alphabétique.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * Recopiez ici un avis reçu sur Airbnb ou Booking, puis passez-le en « Approuvé » pour qu'il apparaisse.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * Tel qu'il apparaît sur la plateforme.
   */
  guestName: string;
  /**
   * Affichée sous l'avis.
   */
  source?: ('airbnb' | 'booking' | 'google' | 'direct') | null;
  /**
   * Recopiez l'avis tel quel, dans sa langue d'origine, sans le corriger.
   */
  text: string;
  /**
   * De 1 à 5. Pour Booking, divisez la note par deux.
   */
  rating: number;
  /**
   * La langue dans laquelle l'avis est écrit. Elle sert aux lecteurs d'écran pour le prononcer correctement.
   */
  language?: ('fr' | 'en' | 'nl' | 'de' | 'es') | null;
  /**
   * Le mois du séjour, si vous le connaissez. Transmis à Google avec l'avis.
   */
  stayDate?: string | null;
  /**
   * Seuls les avis « Approuvé » sont visibles sur le site.
   */
  status: 'pending' | 'approved' | 'rejected';
  /**
   * Les avis cochés passent devant les autres, sur toutes les pages.
   */
  featured?: boolean | null;
  /**
   * La maison : repris sur la page « Le gîte ». L'accueil : repris sur la page contact. Le prix : passe en tête sur la page tarifs.
   */
  topics?: ('house' | 'welcome' | 'value')[] | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * Les demandes envoyées par les voyageurs depuis le formulaire du site. Ouvrez un message pour y répondre, puis cochez « Message lu ».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: number;
  subject: string;
  name: string;
  dates?: string | null;
  /**
   * L'adresse à laquelle répondre.
   */
  email: string;
  phone?: string | null;
  message: string;
  /**
   * Cochez quand vous avez répondu, puis enregistrez. Le résumé ne compte que les messages à lire.
   */
  readStatus?: boolean | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * Les personnes qui peuvent se connecter à cet espace. Pour changer votre mot de passe, ouvrez votre compte.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Affiché sur le résumé pour vous saluer.
   */
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Quand l'adresse d'une page change, l'ancienne renvoie vers la nouvelle : les liens déjà partagés et Google arrivent toujours au bon endroit. Changer l'adresse d'un guide ajoute sa ligne ici tout seul.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * L'adresse qui n'existe plus. Vous pouvez la coller en entier, elle sera raccourcie toute seule. Elle vaut pour le site en français et en anglais.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    /**
     * Si ce guide change d'adresse plus tard, le renvoi suit tout seul.
     */
    reference?: {
      relationTo: 'guides';
      value: number | Guide;
    } | null;
    /**
     * Une page du site, par exemple /le-gite, ou l'adresse entière d'un autre site.
     */
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "places_select".
 */
export interface PlacesSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  commune?: T;
  summary?: T;
  image?: T;
  address?: T;
  geocodedAddress?: T;
  driveMin?: T;
  driveKm?: T;
  routeMessage?: T;
  lat?: T;
  lng?: T;
  positionLocked?: T;
  website?: T;
  events?:
    | T
    | {
        name?: T;
        period?: T;
        id?: T;
      };
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides_select".
 */
export interface GuidesSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  image?: T;
  body?: T;
  practical?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  checkedAt?: T;
  sources?:
    | T
    | {
        name?: T;
        url?: T;
        id?: T;
      };
  places?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        shareTitle?: T;
      };
  theme?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "official-sites_select".
 */
export interface OfficialSitesSelect<T extends boolean = true> {
  name?: T;
  url?: T;
  detail?: T;
  group?: T;
  order?: T;
  showInFooter?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "amenities_select".
 */
export interface AmenitiesSelect<T extends boolean = true> {
  name?: T;
  icon?: T;
  category?: T;
  enabled?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  guestName?: T;
  source?: T;
  text?: T;
  rating?: T;
  language?: T;
  stayDate?: T;
  status?: T;
  featured?: T;
  topics?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  subject?: T;
  name?: T;
  dates?: T;
  email?: T;
  phone?: T;
  message?: T;
  readStatus?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  creditUrl?: T;
  blurDataURL?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        share?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * La première page que voient les visiteurs. Les onglets suivent l'ordre de la page, de haut en bas.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  /**
   * Le titre principal de la page. Google le lit en premier : gardez le lieu et le mot gîte ou maison dedans. Ce qui suit la première virgule s'affiche sur une seconde ligne.
   */
  title: string;
  /**
   * Deux ou trois phrases sous le titre.
   */
  lede?: string | null;
  /**
   * La grande photo affichée derrière le titre. Choisissez une photo lumineuse, en largeur. Elle ne sert que si le film d'accueil ne peut pas se lancer.
   */
  image?: (number | null) | Media;
  /**
   * Le titre du bloc « La maison ».
   */
  houseTitle?: string | null;
  /**
   * Le paragraphe du bloc « La maison ».
   */
  houseText?: string | null;
  /**
   * Le titre au-dessus de la carte des temps de route.
   */
  surroundingsTitle?: string | null;
  /**
   * Le paragraphe au-dessus de la carte des temps de route.
   */
  surroundingsText?: string | null;
  /**
   * Quatre lieux affichés en grandes cartes sous la carte des temps de route. Choisissez des lieux qui ont une photo.
   */
  featuredPlaces?: (number | Place)[] | null;
  /**
   * Le titre au-dessus des avis des voyageurs.
   */
  reviewsTitle?: string | null;
  /**
   * Le titre au-dessus des guides.
   */
  guidesTitle?: string | null;
  /**
   * Le paragraphe au-dessus des guides.
   */
  guidesText?: string | null;
  /**
   * Six guides au plus, affichés dans cet ordre. Faites glisser pour changer l'ordre.
   */
  featuredGuides?: (number | Guide)[] | null;
  /**
   * Le titre de l'appel à réserver.
   */
  bookingTitle?: string | null;
  /**
   * Le paragraphe de l'appel à réserver.
   */
  bookingText?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * La photo de fond de l'image affichée quand la page est partagée. Laissez vide pour reprendre la photo d'en-tête.
     */
    image?: (number | null) | Media;
    /**
     * Le titre écrit en grand sur l'image qui s'affiche quand la page est partagée sur WhatsApp, Facebook ou par SMS. Quatre à six mots. Pour un guide, laissez vide : le début de son titre est repris.
     */
    shareTitle?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * La visite de la maison, pièce par pièce. Les équipements se gèrent dans « Équipements du gîte ».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cottage-page".
 */
export interface CottagePage {
  id: number;
  /**
   * Le titre principal de la page. Google le lit en premier : gardez le lieu et le mot gîte ou maison dedans.
   */
  title: string;
  /**
   * Deux ou trois phrases sous le titre.
   */
  lede?: string | null;
  /**
   * La grande photo affichée derrière le titre. Choisissez une photo lumineuse, en largeur.
   */
  image?: (number | null) | Media;
  /**
   * Deux paragraphes suffisent : ce qu'est la maison, où elle se trouve, ce qui la rend agréable.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Une ligne par pièce ou par espace (séjour, cuisine, chaque chambre, jardin). L'ordre est celui de la visite : faites glisser une ligne pour la déplacer.
   */
  rooms?:
    | {
        name: string;
        /**
         * Range la pièce au bon étage de la visite.
         */
        level?: ('ground' | 'upstairs' | 'outdoors') | null;
        /**
         * Le couchage ou l'équipement principal, affiché sous le nom de la pièce.
         */
        details?: string | null;
        /**
         * Deux phrases au plus, à côté des photos.
         */
        description?: string | null;
        /**
         * Une à trois photos. La première sert aussi sur la page d'accueil.
         */
        photos?:
          | {
              image: number | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Détails de décoration et ambiances qui ne sont rattachés à aucune pièce.
   */
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * La photo de fond de l'image affichée quand la page est partagée. Laissez vide pour reprendre la photo d'en-tête.
     */
    image?: (number | null) | Media;
    /**
     * Le titre écrit en grand sur l'image qui s'affiche quand la page est partagée sur WhatsApp, Facebook ou par SMS. Quatre à six mots. Pour un guide, laissez vide : le début de son titre est repris.
     */
    shareTitle?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Que faire autour du gîte. Les lieux eux-mêmes se gèrent dans « Lieux aux alentours ».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "surroundings-page".
 */
export interface SurroundingsPage {
  id: number;
  /**
   * Le titre principal de la page. Google le lit en premier : gardez le lieu et le mot gîte ou maison dedans.
   */
  title: string;
  /**
   * Deux ou trois phrases sous le titre.
   */
  lede?: string | null;
  /**
   * La grande photo affichée derrière le titre. Choisissez une photo lumineuse, en largeur.
   */
  image?: (number | null) | Media;
  /**
   * Où se trouve Romorantin et ce qu'on atteint dans chaque direction.
   */
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  headings?: {
    chateaux?: string | null;
    famille?: string | null;
    nature?: string | null;
    villages?: string | null;
    terroir?: string | null;
    loire?: string | null;
    romorantin?: string | null;
    pratique?: string | null;
  };
  /**
   * Le titre du bloc pour les cavaliers.
   */
  equestrianTitle?: string | null;
  /**
   * Ce qui intéresse un cavalier : distance du Parc équestre fédéral de Lamotte-Beuvron, stationnement du van, horaires d'arrivée souples.
   */
  equestrianText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * La photo de fond de l'image affichée quand la page est partagée. Laissez vide pour reprendre la photo d'en-tête.
     */
    image?: (number | null) | Media;
    /**
     * Le titre écrit en grand sur l'image qui s'affiche quand la page est partagée sur WhatsApp, Facebook ou par SMS. Quatre à six mots. Pour un guide, laissez vide : le début de son titre est repris.
     */
    shareTitle?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * La page qui liste tous les guides. Les guides eux-mêmes se gèrent dans « Guides de séjour ».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides-page".
 */
export interface GuidesPage {
  id: number;
  /**
   * Le titre principal de la page. Google le lit en premier : gardez le lieu et le mot gîte ou maison dedans.
   */
  title: string;
  /**
   * Deux ou trois phrases sous le titre. Écrivez {count} à l'endroit où le nombre de guides doit s'afficher.
   */
  lede?: string | null;
  /**
   * La grande photo affichée derrière le titre. Choisissez une photo lumineuse, en largeur. Laissez vide pour reprendre la photo du guide mis en avant.
   */
  image?: (number | null) | Media;
  /**
   * Au-dessus du premier guide, celui qui cite le plus de lieux.
   */
  leadTitle?: string | null;
  /**
   * Au-dessus de tous les autres guides, classés par thème.
   */
  allTitle?: string | null;
  themeSites?: {
    chateaux?: (number | OfficialSite)[] | null;
    equestre?: (number | OfficialSite)[] | null;
    famille?: (number | OfficialSite)[] | null;
    nature?: (number | OfficialSite)[] | null;
    villages?: (number | OfficialSite)[] | null;
    terroir?: (number | OfficialSite)[] | null;
    loire?: (number | OfficialSite)[] | null;
    romorantin?: (number | OfficialSite)[] | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * La photo de fond de l'image affichée quand la page est partagée. Laissez vide pour reprendre la photo d'en-tête.
     */
    image?: (number | null) | Media;
    /**
     * Le titre écrit en grand sur l'image qui s'affiche quand la page est partagée sur WhatsApp, Facebook ou par SMS. Quatre à six mots. Pour un guide, laissez vide : le début de son titre est repris.
     */
    shareTitle?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Les textes de la page tarifs. Les prix, les horaires et les conditions se modifient dans « Tarifs et conditions ».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rates-page".
 */
export interface RatesPage {
  id: number;
  /**
   * Le titre principal de la page. Google le lit en premier : gardez le lieu et le mot gîte ou maison dedans.
   */
  title: string;
  /**
   * Deux ou trois phrases sous le titre.
   */
  lede?: string | null;
  /**
   * La grande photo affichée derrière le titre. Choisissez une photo lumineuse, en largeur.
   */
  image?: (number | null) | Media;
  /**
   * Le titre du bloc « Comment réserver ».
   */
  stepsTitle?: string | null;
  /**
   * Le paragraphe à droite du titre : ce que les voyageurs gagnent à vous écrire directement.
   */
  directBooking?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Trois étapes exactement, affichées en trois colonnes dans cet ordre.
   */
  steps?:
    | {
        title: string;
        /**
         * Deux phrases. Écrivez {sejour_minimum} pour afficher la durée minimale du séjour réglée dans « Tarifs et conditions ».
         */
        text: string;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * La photo de fond de l'image affichée quand la page est partagée. Laissez vide pour reprendre la photo d'en-tête.
     */
    image?: (number | null) | Media;
    /**
     * Le titre écrit en grand sur l'image qui s'affiche quand la page est partagée sur WhatsApp, Facebook ou par SMS. Quatre à six mots. Pour un guide, laissez vide : le début de son titre est repris.
     */
    shareTitle?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Les textes de la page contact. Téléphone, e-mail, adresse et itinéraires se modifient dans « Le gîte et ses coordonnées ».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  /**
   * Le titre principal de la page. Google le lit en premier : gardez le lieu et le mot gîte ou maison dedans.
   */
  title: string;
  /**
   * Deux ou trois phrases sous le titre.
   */
  lede?: string | null;
  /**
   * La grande photo affichée derrière le titre. Choisissez une photo lumineuse, en largeur.
   */
  image?: (number | null) | Media;
  /**
   * Deux phrases signées de vos prénoms. Un avis de voyageur sur l'accueil s'affiche juste en dessous.
   */
  hostsNote?: string | null;
  form: {
    /**
     * Un formulaire court est rempli plus volontiers : ne rendez le téléphone obligatoire que si vous rappelez vraiment.
     */
    phoneField: 'hidden' | 'optional' | 'required';
    /**
     * Avec les dates, vous pouvez répondre tout de suite sur les disponibilités.
     */
    datesField: 'hidden' | 'optional' | 'required';
    /**
     * Montre au voyageur comment écrire ses dates. Laissez vide pour garder l'exemple habituel.
     */
    datesHint?: string | null;
    /**
     * Laissez vide pour garder « Message envoyé ».
     */
    sentTitle?: string | null;
    /**
     * Dites au voyageur sous combien de temps vous répondez. Laissez vide pour garder le texte habituel.
     */
    sentText?: string | null;
  };
  /**
   * Le titre de l'appel à réserver en bas de page.
   */
  bookingTitle?: string | null;
  /**
   * Le paragraphe de l'appel à réserver en bas de page.
   */
  bookingText?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * La photo de fond de l'image affichée quand la page est partagée. Laissez vide pour reprendre la photo d'en-tête.
     */
    image?: (number | null) | Media;
    /**
     * Le titre écrit en grand sur l'image qui s'affiche quand la page est partagée sur WhatsApp, Facebook ou par SMS. Quatre à six mots. Pour un guide, laissez vide : le début de son titre est repris.
     */
    shareTitle?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Tout ce qui décrit le gîte et sert sur plusieurs pages : capacité, coordonnées, annonces Airbnb et Booking, questions fréquentes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  propertyDetails: {
    /**
     * La surface habitable.
     */
    surface: number;
    /**
     * Comme sur vos annonces.
     */
    maxGuests: number;
    /**
     * Les pièces fermées avec un lit.
     */
    bedrooms: number;
    /**
     * Avec douche ou baignoire.
     */
    bathrooms: number;
    /**
     * Affiché dans la fiche du gîte et dans les questions sur les tarifs.
     */
    petsAllowed?: boolean | null;
  };
  /**
   * Ce paragraphe n'apparaît pas sur les pages : il décrit le gîte à Google et aux assistants comme ChatGPT.
   */
  siteDescription?: string | null;
  /**
   * Affiché sur la page contact, en pied de page et sur la page tarifs.
   */
  hosts?: string | null;
  contact?: {
    /**
     * L'adresse affichée sur le site. Les messages du formulaire y arrivent aussi.
     */
    email?: string | null;
    /**
     * Laissez vide pour ne pas afficher de numéro.
     */
    phone?: string | null;
    /**
     * Affichée sur la page contact et dans le pied de page.
     */
    address?: string | null;
    /**
     * Cinq chiffres.
     */
    postalCode?: string | null;
    /**
     * Le nom complet de la commune.
     */
    city?: string | null;
    coordinates?: {
      /**
       * La position nord-sud de la maison.
       */
      lat?: number | null;
      /**
       * La position est-ouest : le second nombre donné par Google Maps.
       */
      lng?: number | null;
      /**
       * Sur la page contact. 13 montre la ville, 16 montre la rue.
       */
      zoom?: number | null;
      /**
       * Affiché quand on touche le repère de la carte.
       */
      markerLabel?: string | null;
    };
  };
  /**
   * Une ligne par ville de départ.
   */
  accessRoutes?:
    | {
        /**
         * La ville de départ.
         */
        from: string;
        /**
         * En voiture.
         */
        duration: string;
        /**
         * Par la route.
         */
        distance: string;
        /**
         * Les routes principales, en une ligne.
         */
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Une ligne par plateforme. Mettez la note et le nombre d'avis à jour quand ils changent sur la plateforme.
   */
  platforms?:
    | {
        /**
         * Le site où se trouve l'annonce.
         */
        platform: 'airbnb' | 'booking' | 'google' | 'gites-de-france' | 'other';
        /**
         * Ouvrez votre annonce et copiez l'adresse affichée en haut du navigateur.
         */
        url: string;
        /**
         * La note affichée sur votre annonce, avec un point : 4.9.
         */
        rating?: number | null;
        /**
         * 5 pour Airbnb, 10 pour Booking.
         */
        ratingScale?: number | null;
        /**
         * Le total affiché sur l'annonce.
         */
        reviewCount?: number | null;
        /**
         * Une distinction décernée par la plateforme, si vous en avez une.
         */
        badge?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Collez ici le lien d'export du calendrier de chaque plateforme : la page tarifs affiche alors les nuits libres et prises des prochains mois, mises à jour toutes les deux heures. Ces liens sont privés, ils ne sont jamais montrés aux visiteurs. Laissez vide pour ne pas afficher le calendrier.
   */
  calendars?: {
    /**
     * Sur Airbnb : Calendrier, Disponibilité, Connecter les calendriers, Exporter le calendrier. Copiez le lien qui finit par .ics.
     */
    airbnb?: string | null;
    /**
     * Sur l'extranet Booking : Tarifs et disponibilités, Synchroniser les calendriers, Exporter le calendrier. Copiez le lien proposé.
     */
    booking?: string | null;
  };
  /**
   * Les questions que les voyageurs vous posent vraiment. Les questions sur les prix sont écrites automatiquement sur la page tarifs.
   */
  faqs?:
    | {
        question: string;
        /**
         * Une réponse directe, en deux ou trois phrases.
         */
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * La ligne écrite sous le nom du gîte, à la première visite du site.
   */
  tagline?: string | null;
  /**
   * Affichée en grand quand le film se termine, au-dessus des boutons de réservation.
   */
  filmEndTitle?: string | null;
  socialLinks?: {
    /**
     * Ouvrez votre page et copiez l'adresse affichée en haut du navigateur.
     */
    facebook?: string | null;
    /**
     * L'adresse complète de votre profil.
     */
    instagram?: string | null;
    /**
     * Laissez vide si vous n'en avez pas.
     */
    pinterest?: string | null;
    /**
     * Laissez vide si vous n'en avez pas.
     */
    youtube?: string | null;
    /**
     * Laissez vide si vous n'en avez pas.
     */
    tiktok?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Les prix relevés sur Airbnb et Booking, les horaires d'arrivée et de départ, les conditions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-config".
 */
export interface PricingConfig {
  id: number;
  currency?: string | null;
  /**
   * Une ligne par cas : un nombre de voyageurs et une durée. Le site calcule tout seul le prix par nuit.
   */
  quotes?:
    | {
        /**
         * Le nombre de voyageurs saisi dans la recherche sur la plateforme.
         */
        guests: '2' | '4' | '6';
        /**
         * Le nombre de nuits saisi dans la recherche sur la plateforme.
         */
        nights: '2' | '7';
        /**
         * Recopiez le prix total affiché par Airbnb pour ce nombre de nuits et de voyageurs, taxes et frais inclus. Ne recopiez pas un prix en promotion (prix barré) : prenez le prix normal. Laissez vide si vous ne l'avez pas relevé.
         */
        airbnb?: number | null;
        /**
         * Recopiez le prix total affiché par Booking pour ce nombre de nuits et de voyageurs, taxes et frais inclus, au tarif avec annulation gratuite. Laissez vide si vous ne l'avez pas relevé.
         */
        booking?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Le plus petit nombre de nuits que les plateformes acceptent.
   */
  minimumStay?: number | null;
  /**
   * Le jour où vous avez recopié les prix. Cette date s'affiche sur le site à côté des prix.
   */
  quotedOn?: string | null;
  /**
   * Votre réponse à cette question, en une ou deux phrases. Elle s'affiche dans les questions fréquentes de la page tarifs. Laissez vide pour retirer la question.
   */
  note?: string | null;
  /**
   * À laisser vide tant que les prix des plateformes sont déjà taxes et frais inclus. N'ajoutez une ligne que pour un vrai supplément facturé en plus.
   */
  additionalFees?:
    | {
        /**
         * Le nom du supplément, tel qu'il s'affiche sur la page tarifs.
         */
        name: string;
        /**
         * En euros, sans le symbole.
         */
        amount: number;
        /**
         * Par séjour : compté une fois. Par nuit : compté chaque nuit. Par personne : compté pour chaque voyageur.
         */
        type?: ('per_stay' | 'per_night' | 'per_person') | null;
        /**
         * Une précision affichée sous le montant. Facultatif.
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  policies?: {
    /**
     * Jusqu'à quand un voyageur peut annuler et ce qui lui est remboursé.
     */
    cancellation?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Le montant de l'acompte et de la caution, et la façon de les régler.
     */
    deposit?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Affichée sur la page tarifs après le mot « Arrivée ». Écrivez l'heure en chiffres, avec un h : Google la lit aussi.
     */
    checkIn?: string | null;
    /**
     * Affichée sur la page tarifs après le mot « Départ ». Écrivez l'heure en chiffres, avec un h : Google la lit aussi.
     */
    checkOut?: string | null;
    /**
     * Ce qu'il faut savoir avant de réserver : ménage, linge, animaux.
     */
    additional?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  title?: T;
  lede?: T;
  image?: T;
  houseTitle?: T;
  houseText?: T;
  surroundingsTitle?: T;
  surroundingsText?: T;
  featuredPlaces?: T;
  reviewsTitle?: T;
  guidesTitle?: T;
  guidesText?: T;
  featuredGuides?: T;
  bookingTitle?: T;
  bookingText?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        shareTitle?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cottage-page_select".
 */
export interface CottagePageSelect<T extends boolean = true> {
  title?: T;
  lede?: T;
  image?: T;
  description?: T;
  rooms?:
    | T
    | {
        name?: T;
        level?: T;
        details?: T;
        description?: T;
        photos?:
          | T
          | {
              image?: T;
              id?: T;
            };
        id?: T;
      };
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        shareTitle?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "surroundings-page_select".
 */
export interface SurroundingsPageSelect<T extends boolean = true> {
  title?: T;
  lede?: T;
  image?: T;
  intro?: T;
  headings?:
    | T
    | {
        chateaux?: T;
        famille?: T;
        nature?: T;
        villages?: T;
        terroir?: T;
        loire?: T;
        romorantin?: T;
        pratique?: T;
      };
  equestrianTitle?: T;
  equestrianText?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        shareTitle?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides-page_select".
 */
export interface GuidesPageSelect<T extends boolean = true> {
  title?: T;
  lede?: T;
  image?: T;
  leadTitle?: T;
  allTitle?: T;
  themeSites?:
    | T
    | {
        chateaux?: T;
        equestre?: T;
        famille?: T;
        nature?: T;
        villages?: T;
        terroir?: T;
        loire?: T;
        romorantin?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        shareTitle?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rates-page_select".
 */
export interface RatesPageSelect<T extends boolean = true> {
  title?: T;
  lede?: T;
  image?: T;
  stepsTitle?: T;
  directBooking?: T;
  steps?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        shareTitle?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  title?: T;
  lede?: T;
  image?: T;
  hostsNote?: T;
  form?:
    | T
    | {
        phoneField?: T;
        datesField?: T;
        datesHint?: T;
        sentTitle?: T;
        sentText?: T;
      };
  bookingTitle?: T;
  bookingText?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        shareTitle?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  propertyDetails?:
    | T
    | {
        surface?: T;
        maxGuests?: T;
        bedrooms?: T;
        bathrooms?: T;
        petsAllowed?: T;
      };
  siteDescription?: T;
  hosts?: T;
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
        postalCode?: T;
        city?: T;
        coordinates?:
          | T
          | {
              lat?: T;
              lng?: T;
              zoom?: T;
              markerLabel?: T;
            };
      };
  accessRoutes?:
    | T
    | {
        from?: T;
        duration?: T;
        distance?: T;
        description?: T;
        id?: T;
      };
  platforms?:
    | T
    | {
        platform?: T;
        url?: T;
        rating?: T;
        ratingScale?: T;
        reviewCount?: T;
        badge?: T;
        id?: T;
      };
  calendars?:
    | T
    | {
        airbnb?: T;
        booking?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  tagline?: T;
  filmEndTitle?: T;
  socialLinks?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        pinterest?: T;
        youtube?: T;
        tiktok?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-config_select".
 */
export interface PricingConfigSelect<T extends boolean = true> {
  currency?: T;
  quotes?:
    | T
    | {
        guests?: T;
        nights?: T;
        airbnb?: T;
        booking?: T;
        id?: T;
      };
  minimumStay?: T;
  quotedOn?: T;
  note?: T;
  additionalFees?:
    | T
    | {
        name?: T;
        amount?: T;
        type?: T;
        description?: T;
        id?: T;
      };
  policies?:
    | T
    | {
        cancellation?: T;
        deposit?: T;
        checkIn?: T;
        checkOut?: T;
        additional?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GuideProgrammeBlock".
 */
export interface GuideProgrammeBlock {
  /**
   * Une ligne par étape, dans l'ordre de la journée : l'heure, ce qu'on fait, puis le détail utile (durée, tarif, où se garer).
   */
  steps: {
    time: string;
    title: string;
    /**
     * Durée sur place, tarif, conseil. Deux ou trois phrases au plus.
     */
    details?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'programme';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}